### ISSUE TITLE
Add mastodon as an option to member accounts

### ISSUE THREAD

**Issue by mikestreety** [Virtual-Coffee/virtualcoffee.io#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

When adding myself to the members list earlier, I was surprised not to find `mastodon` as an available option for accounts to add a little mastodon speech bubble.

### Proposed solution

I'm happy to look into adding this, adding `mastodon` as the `type`, but allowing `url` as the parameter rather than `username` or similar, so people can link to their instances.

E.g. 

```js
accounts: [
    { type: 'mastodon', url: 'https://hachyderm.io/@mikestreety' },
]
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment]
@mikestreety I'd say go for it! Having the full url makes sense here, since the servers can be different 👍🏼
