### ISSUE TITLE
Add anchor link on member map `<Popup>` to member block

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

It'd be cool in the popover on the map pins to be able to link to the user's info.

![image](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/360261/33e5015a-477e-4121-9a4c-33bc956266b2)

### Proposed solution

The member cards already have an id attached to them:

https://github.com/Virtual-Coffee/virtualcoffee.io/blob/bddbe981153d7f3fa1c06bdf104dc122f3b0d9f4/app/components/MemberCards.tsx#L41

So we can update the Popover in the map to have an anchor-style link to the card (`<a href="#member_danieltott">Dan Ott</a>`)

The popovers are created here:

https://github.com/Virtual-Coffee/virtualcoffee.io/blob/bddbe981153d7f3fa1c06bdf104dc122f3b0d9f4/app/components/MemberMap.tsx#L26-L34C14

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by piotrszymaniec** [comment]
could i take it ? :)

**Comment by danieltott** [comment]
@piotrszymaniec it's all you!
