### ISSUE TITLE
Update Volunteering docs

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

Edit/Clarification on existing content

### URL of existing page

 https://virtualcoffee.io/resources/virtual-coffee-handbook/get-involved/paths-to-leadership

### Context for content change

Looking through the requirements, I noticed that there's a lot of commitment that we don't actually require. No one should ever be required to volunteer more than 5 hours per **month** for any position. 

Room leaders/notetakers could volunteer 2 hours/mo. 

Let's remove qualifications altogether. Instead, let's have a note at the beginning that says something like, "Our mission is to provide meaningful opportunities for learning, leadership, and contribution to our members. Below, you'll find a list of leadership opportunities for members who are in good standing and are willing to support the community."

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by CBID2** [comment]
I'll work on this @BekahHW! 😀 It's been a while since I contributed to Virtual Coffee! 😃
