### ISSUE TITLE
feat: Remove CodeSee

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/virtualcoffee.io#1176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

We still have a check that runs CodeSee as below screenshot:

![GH actions checks](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/45172775/43bcd0f4-598f-475b-9f51-5079aeeb0098)

### Proposed solution

As CodeSee already [shut down](https://www.linkedin.com/feed/update/urn:li:activity:7163970333912289281/), we might want to consider to remove CodeSee from our actions and replace it with something similar if we still need the function.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment]
All this would take is deleting `.github/workflows/codesee-arch-diagram.yml`

**Comment by manya706** [comment]
hi! can i take this?
