### ISSUE TITLE
Add link to "Join Virtual Coffee" page to the nav bar

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/virtualcoffee.io#1182]
### Issue Context

Based on the conversation on Slack with @BekahHW, it's now quite challenging for folks who wants to join VC to find information about how to join VC and what can they expect from joining VC.

### Proposed solution

Add a link to `/resources/virtual-coffee-handbook/join-virtual-coffee` to the Nav Bar with the text "Join". I like @eternalmaha 's idea of putting it before Store.

No need to change the page location at all - just a straight link will do 👍

`<Nav />` is located at `src/components/Nav.tsx`

**Comment by maha4peace** [comment]
Hey! I'd love to work on this issue! I think it's a great idea to have multiple locations to direct people to join the club!  I like the idea of adding "FAQ"  before the "Store" link since It'll flow nicely after them learning stuff from "Resource".

**Comment by adiati98** [comment]
Hey @maha4peace,

Thank you for your interest in this issue ✨ 

However, this issue is still on triage and waiting approval on which way we'll go from our maintainers, @BekahHW and @danieltott.

That said, please refrain from working on anything until it gets a green light. Thanks. 🙂

**Comment by maha4peace** [comment]
gotcha!! Thank you for letting me know :) Is there a key to refer to that breaks down all the different tags (ie. "triage")

**Comment by danieltott** [comment]
@eternalmaha I know this was a while ago, but this issue is ready to be worked on. Are you still interested?

**Comment by krishnaagrawal7508** [comment]
@danieltott Hey! I'd love to work on this issue! I am submitting a PR for this issue
