### ISSUE TITLE
Update newsletter subscribe

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#1191]
We're moving newsletter providers, so we need to make sure ppl are subscribing in the right place.

Find where we've pointed people to subscribe (previously Mailchimp) and point them to the new subscription: https://virtualcoffeeio.beehiiv.com/subscribe

**Comment by thesarfo** [comment]
may I work on this?

**Comment by danieltott** [comment]
@thesarfo it's all you!
