### ISSUE TITLE
Can't sign up for newsletter

### ISSUE THREAD

**Issue by ebanner** [Virtual-Coffee/virtualcoffee.io#1201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Tried to sign up for the VC newsletter and I got this error

![image](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/2068912/a832399f-18f0-4e98-9bca-8b4b566804a9)

### Steps To Reproduce

Go to VC website
Click on sign up for newsletter
Enter your email
Click submit

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by ebanner** [comment]
cc @BekahHW

**Comment by meg-gutshall** [comment]
Relates to #1191

**Comment by danieltott** [comment]
Fixed in de7b839f80b143cf52ae2d00cfd8a66161c23265
