### ISSUE TITLE
Close nav menu when clicking nav item

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#1234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On mobile, when you click a link in the header navigation, the page navigates but the menu stays open.

### Steps To Reproduce

- Open the site in a mobile-sized window (or on a mobile device)
- Open the navigation menu
- Click one of the non-store items

### Solution
I believe this will be as easy as adding an `onClick` to the link items that sets `isOpen` to `false`.

**Comment by krishnaagrawal7508** [comment]
hey, can u assign me this!

**Comment by manya706** [comment]
hi! can i work on this?

**Comment by Dyslex7c** [comment]
hello, I am new here. Can I work on this?

**Comment by Hasan36arnob** [comment]
hey can I work on this?
