### ISSUE TITLE
Hacktoberfest 2024: Give yourself the Hacktoberfest 2024 Badge!

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#1240]
> [!IMPORTANT]  
> **Please note - only PRs from existing Virtual Coffee members participating in the Virtual Coffee Hacktoberfest Initiative will be accepted.**

### First step - complete #13 if you haven't already!

If you haven't completed #13 already, it is perfectly fine to do that _and_ this in the same Pull Request.

> [!WARNING]
> If you have previously forked this repo, please make sure you **update your fork** before starting work. The location of these files has moved. We will not be able to accept your pull request until this is done!

### Steps:
- Find your member file (it will be `src/content/members/members/yourgithubuser.ts` where `yourgithubuser` is your user name on github.
- Near the end of the file, find the `badges` array, and add `'Hacktoberfest 2024'`:

  ```js
  badges: ['Hacktoberfest2022', 'Hacktoberfest2023', 'Hacktoberfest2024'],
  ```
  (Only include previous year's badges if you also participated in those years)
- Save, commit, and file a Pull Request!
- Bonus: while you're in there, take a look at the `flare` section for a little bit of fun if you haven't yet 😁

Our [original issue for adding your member profile](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13) has a lot of details about previewing locally and interacting with GitHub - definitely check that out if you'd like to preview locally!

**Comment by meg-gutshall** [comment]
Hacktoberfest 2024 is now over.
