### ISSUE TITLE
feat: Add End Time to Events Page

### ISSUE THREAD

**Issue by meg-gutshall** [Virtual-Coffee/virtualcoffee.io#1271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

Since the duration of our events varies, I would like our Events pages on the website to show the end time in addition to the start time.
While hosting Accountabilibuddies, there have been several occasions in which attendees weren't aware that the event was longer than an hour, despite this being written in the event's description. I think it will help if we add this info in a more prominent spot.

### Proposed solution

I think we should add this information to the event card headers. I created a mockup below.

<img width="1255" alt="vcio-events-page-mockup" src="https://github.com/user-attachments/assets/c1ae1f9e-5cd4-4cc7-9b97-6e95fd78533c">

### Alternatives Considered

I'm open to any other suggestions! We could keep the card header as it is and add the event duration somewhere on the card.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by codewithjazzy** [comment]
@meg-gutshall Hi 👋🏾 I'm here and ready
