### ISSUE TITLE
Fix: apostrophe not rendered

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#1273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The apostrophe character in the Healthy Habits text is rendering as &apos; instead of an actual apostrophe symbol (').

<img width="527" alt="image" src="https://github.com/user-attachments/assets/feddc205-0fc2-48c5-9c1a-5d1c1be4a356">

### Steps To Reproduce

1. Go to https://virtualcoffee.io/monthlychallenges
2. Scroll to Healthy Habits for Happy Devs. See the description.

### What browsers are you seeing the problem on?

Chrome

### Environment

```markdown
- OS: Mac
- Node:
- pnpm:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by eternalmaha** [comment]
Hello! I'd be glad to take this issue on! I believe I have to wait till it's no longer in triage, right? @meg-gutshall @BekahHW :)

**Comment by meg-gutshall** [comment]
Sorry, @eternalmaha I totally didn't see your comment!

Fixed by #1302

**Comment by eternalmaha** [comment]
No worries @meg-gutshall :)
