### ISSUE TITLE
Update copy on November monthly challenge

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#128]
## Issue Context

November has come and gone! We need to update the copy on the [November Monthly Challenge](https://virtualcoffee.io/monthlychallenges/nov-2020/) to signify that the challenge is over. Doesn't have to be a massive rewrite - just changing the tenses and some headlines will probably be enough. Maybe a short summary?

## Alternatives Considered

Another option would be to leave the page as is, except add an update at the top saying something like "This challenge is over! We did a great job etc etc and are leaving the challenge page up for historical purposes" or something?

**Comment by sethburtonhall** [comment]
Hey @danieltott I just signed up for tomorrow Virtual Coffee and I am looking forward to this. I am also interested in contributing and this could be a good issue for me to get the repo running locally. Are there any mocks or could I just fork and provide a few examples? Thanks!!

**Comment by danieltott** [comment]
Hey @sethburtonhall - it'll be great to have you there! 

Go ahead if you'd like - there aren't any mocks or anything, this is mostly just copy changes. I'm open to ideas for sure - but definitely don't expect any large design changes here. Definitely a good one to get started on!

Let me know if you have any questions or run into any issues - our [README](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/README.md) has the steps for setup and you should be good to go from there!

**Comment by danieltott** [comment]
Closed via #169 - thanks again @sethburtonhall !
