### ISSUE TITLE
fix text in PR template

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There's a typo in the PR template: "This section explains why the above changes explained were done."
<img width="695" alt="image" src="https://github.com/user-attachments/assets/9d1d98ea-5b8b-4a2d-b670-56a8fc0eb86a">

### Steps To Reproduce

1. In the .github folder, find the PR template.
2. Update the text to "This section explains why the above changes were made."

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by saksham-malhotra-27** [comment]
Hey @BekahHW ! is this still open ?

**Comment by meg-gutshall** [comment]
Hi @saksham-malhotra-27! Sorry we did not see your comment earlier. This issue has been fixed by #1300.
