### ISSUE TITLE
CONTRIBUTING.md table of contents contains two missing sections

### ISSUE THREAD

**Issue by dominicduffin1** [Virtual-Coffee/virtualcoffee.io#132]
## Context for documentation change

Noticed that the table of contents in `CONTRIBUTING.md` contains the sections _Preferred code style_ and _Commit message conventions_ which don't exist in the document. This is potentially offputting for contributors who may think there is information they need to know but that they can't find.

## Proposed solution

If the team are planning to publish guidelines on these areas shortly it may make sense to leave as is until then. Otherwise I suggest removing the sections from the table of contents.

**Comment by danieltott** [comment]
@dominicduffin1 good call! Interested in doing a PR?

**Comment by dominicduffin1** [comment]
@danieltott Yeah can do! Are we removing the two sections?

**Comment by danieltott** [comment]
Yeah I think that's the right call for right now. Thank you!!

**Comment by danieltott** [comment]
Fixed in #133 

Thanks again @dominicduffin1 !!
