### ISSUE TITLE
Add PWA (Progressive Web App) support

### ISSUE THREAD

**Issue by sumitkharche** [Virtual-Coffee/virtualcoffee.io#134]
## Issue Context

The lighthouse score for virtualcoffee.io is looking good and site is also mobile friendly. So it would be great if we could add PWA into site which gives users a native applications feel and works offline, works well in low networks and an icon on the phone‘s home screen.

## Suggested Solution
While looking at quick way to make our site as PWA, I found Google workbox would be good and for 11ty we have already a plugin available which uses Google Workbox under hood. 

## Additional Resources

https://www.npmjs.com/package/eleventy-plugin-pwa

**Comment by sumitkharche** [comment]
Created above draft PR to verify the PWA integration.

**Comment by danieltott** [comment]
Closed via #135
