### ISSUE TITLE
Members Section Failing to Build Completely

### ISSUE THREAD

**Issue by joshuatz** [Virtual-Coffee/virtualcoffee.io#174]
## Describe the bug

As [described in the slack today](https://virtual-coffee-group.slack.com/archives/C017GPJQTLP/p1611274454025400), there seems to be an issue with the members page ([virtualcoffee.io/members/](https://virtualcoffee.io/members/)) - only one member is showing up under the "Our Members" header, despite there being 20+, which normally show up without issue.

## To Reproduce
Head to [https://virtualcoffee.io/members/](https://virtualcoffee.io/members/), and scroll down to "Our Members"

## Expected behavior
All members should show up

## Screenshots / Additional Context

Multiple users were able to repro, as I was too:

![2021-01-21 17_24_37-Virtual Coffee Members](https://user-images.githubusercontent.com/17817563/105432984-963f6780-5c0d-11eb-8367-ea53e2122eb3.png)

Looking at [the last *production* Netlify deploy build](https://app.netlify.com/sites/virtual-coffee-io/deploys/6009d06077722600088cc67a), it was apparent that something went wrong when the build process tried to read the JSON files that power that part of the build off the disk:

![2021-01-21 17_10_17-Deploy details _ Virtual Coffee_virtual-coffee-io — Mozilla Firefox](https://user-images.githubusercontent.com/17817563/105433157-f6360e00-5c0d-11eb-9365-cc98f9da79d5.png)

---

This almost seems like a temporary fluke on Netlify's part, because:

 - I could not reproduce this locally, either in production or non-production builds
 - More importantly, the latest preview deploys do not suffer from this issue, despite them *not* reverting or adding any code that would have significantly altered how those files are read in

**Comment by joshuatz** [comment]
I'm going to do a little more digging to see if I spot anything, but this is literally my first time touching Eleventy 😅

In the meantime, since this could just have been a glitch, someone that has access to the Netlify Admin dashboard could go in and force a new production deploy (despite no new commits), by using `Deploys -> Trigger Deploy -> Deploy Site` (or `Clear Cache and Deploy Site`). Or, someone could add an empty commit (e.g. `git commit --allow-empty -m "Trigger Build"`) and push or PR onto `main`. Or simply wait until the next PR gets merged to see if the next production build works without this issue.

**Comment by danieltott** [comment]
Kicking off a "clear cache and deploy" - we'll see if that clears it up

**Comment by jonoyeong** [comment]
@danieltott I'm seeing the members now (28 of them)! Seems like the clear cache and deploy worked.

**Comment by joshuatz** [comment]
^ Yep - That looks like it did the trick! And the subsequent *github-secret-build-hook* run looks fine too, in logs and on the site.

Just to be safe, I double checked the counts:

Website:
```js
document.querySelectorAll('.membercards')[2].children.length
// > 28
```

Repo: 
```bash
ls src/_data/members -l | grep "json" | wc -l
# 28
```

**Comment by jonathanyeong** [comment]
Can confirm as well!

What are your thoughts on adding a better display for the error [here](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/fe51c61047d1504b908af1ce57670d4b5468b2b3/src/_data/founders.js#L30).

```
catch (e) {
      console.warn(`Unable to read ${file}, skipping and moving on! With error: ${e}`);
    }
```

**Comment by danieltott** [comment]
@jonathanyeong that may not be a bad idea - maybe at least on production builds?

**Comment by danieltott** [comment]
This should be all taken care of now. Thanks @joshuatz !
