### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by saramccombs** [Virtual-Coffee/virtualcoffee.io#2]
1. The README paragraph needs updating with the same, but slightly edited, introduction that is visible on the site itself. 
2. Include the url "virtualcoffee.io" within the readme

**Comment by sethburtonhall** [comment]
Is this still needed? The README copy looks good and the image link goes to the .io site.

**Comment by danieltott** [comment]
@sethburtonhall good call - gonna close this one
