### ISSUE TITLE
Update Brownbag Idea Form

### ISSUE THREAD

**Issue by meg-gutshall** [Virtual-Coffee/virtualcoffee.io#214]
Ref: Discussions with AV Team

## Proposed solution

Add more questions to the form to collect necessary data at time of talk proposal

## Collaborators 

@danieltott 
@BekahHW

**Comment by BekahHW** [comment]
Yes! I need to make a PR with my changes. 

There's two parts here that have to happen and we're looking at a multi-part flow. 

- Some of it will be updating the form.
- Some will be automating things
- Some of it will be first updating docs and then creating a team. 

I can probably get the form updates in a PR this week.

**Comment by danieltott** [comment]
closed via https://github.com/Virtual-Coffee/virtualcoffee.io/pull/215#issuecomment-909246497
