### ISSUE TITLE
Add April Newsletter to the site

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#223]
## Issue Context

Every month, we try to get the newsletter up on the site within a week of sending it out. Currently, we're moving them over "by hand." 

You can look at the existing newsletters ( src > newsletter > issues) as a kind of template. The sections are all the same. The content needs updated, and sometimes that changes the way things look, for example, your list may have fewer items.

### Steps to update
_You can look at the existing newsletters ( src > newsletter > issues) as a kind of template. The sections are all the same. The content needs updated, and sometimes that changes the way things look, for example, your list may have fewer items_

* In the code base, navigate to src > newsletter > issues and create a new file 2021-04.njk
* If you don't get the newsletter, you can use [this link](https://mailchi.mp/a640f543a2b1/what-were-up-to-in-april-celebrating-a-year-of-growth-friends-and-virtual-coffee) to check out the current issue for content to update.
* Add the latest issue using the format from the past issues.

If you have questions, please let us know. We're up for pairing if anyone wants to walk through this!

**Comment by crisbnp** [comment]
I'd like to work on this please. When do you need this by?

**Comment by BekahHW** [comment]
@crisbnp Awesome! I was hoping to get it up by the end of the week, but if that's an issue, let me know.

**Comment by crisbnp** [comment]
@BekahHW Found some time to do this this evening. Let me know what you think.

**Comment by danieltott** [comment]
@crisbnp This is awesome! Great work 💪

**Comment by crisbnp** [comment]
Yay 🎉 thank you! I want to use a gif to reply to this but I don't know how 😂
