### ISSUE TITLE
Add May Newsletter to site

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#237]
## Issue Context

Every month, we try to get the newsletter up on the site within a week of sending it out. Currently, we're moving them over "by hand." 

You can look at the existing newsletters ( src > newsletter > issues) as a kind of template. The sections are all the same. The content needs updated, and sometimes that changes the way things look, for example, your list may have fewer items.

### Steps to update
_You can look at the existing newsletters ( src > newsletter > issues) as a kind of template. The sections are all the same. The content needs updated, and sometimes that changes the way things look, for example, your list may have fewer items_

* In the code base, navigate to src > newsletter > issues and create a new file 2021-05.njk
* If you don't get the newsletter, you can use [this link](https://us7.campaign-archive.com/?u=e52b6b09f8fe23f8277bfbe66&id=36394c340c) to check out the current issue for content to update.
* Add the latest issue using the format from the past issues.

If you have questions, please let us know. We're up for pairing if anyone wants to walk through this!

**Comment by tkshill** [comment]
On it and acknowledged!
