### ISSUE TITLE
Add July Challenge/Theme page

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#260]
## Issue Context

Add July Challenge to the site

## Steps

- [ ] Add folder src > monthlychallenges > july-2021
- [ ] Add index.njk to the file
- [ ] Using [June 2021](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/monthlychallenges/june-2021/index.njk) as kind of a template, create July 2021 from docs in contributors
- [ ] Assign me to review PR once ready.

**Comment by vanessacor** [comment]
If it's still up for grabs I can take this one
