### ISSUE TITLE
Upgrade to bootstrap 5

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#265]
## Issue Context

Currently we're using Bootstrap 4 - it would be great to upgrade to Bootstrap v5

## Suggested Solution

Upgrade to the latest version of bootstrap, and go through their [migration guide](https://getbootstrap.com/docs/5.0/migration/) to address any breaking changes.

**Comment by Lor1138** [comment]
I'll take this one if it is still available!

**Comment by danieltott** [comment]
@Lor1138 you got it! Let me know if you have any questions!

**Comment by meg-gutshall** [comment]
I am going to try to get this done by the end of this weekend, but if not it will be when I get back from Ruby Conf.

**Comment by danieltott** [comment]
@meg-gutshall 
![you do you](https://media.tenor.co/images/939ad84854c1700597720549d38ef40f/tenor.gif)

**Comment by danieltott** [comment]
@meg-gutshall how is this coming? I have some other ideas in the works, so if you haven't done much on it, I think we can set it aside for right now. BUT, if you've made some decent progress, I'd be happy to help get it across the finish line if you want to push up a draft PR!

**Comment by meg-gutshall** [comment]
Thanks for checking in! This got completely lost in the shuffle so if you were thinking of going in a different direction, don't let me hold you up. 👍

**Comment by meg-gutshall** [comment]
I can definitely still do this upgrade though if that remains the plan.

**Comment by meg-gutshall** [comment]
Spoke with @danieltott and this is ON HOLD for now
