### ISSUE TITLE
Add message to June Monthly Challenge page that the challenge has ended

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#266]
## Issue Context

Add a message saying the June challenge has ended, and link to the new challenge:

![image](https://user-images.githubusercontent.com/34313413/123690294-35eacc80-d822-11eb-9bba-70015603f1bf.png)

## Suggested Solution

See [December Challenge page](https://virtualcoffee.io/monthlychallenges/dec-2020/)/repo file for style and message.

**Comment by Andrew-Bush** [comment]
I'll take this one!

**Comment by BekahHW** [comment]
@Andrew-Bush do you need any help on this?

**Comment by teezzan** [comment]
I think it is safe to close this. It has been fixed in #292.
