### ISSUE TITLE
Add Message to the July Monthly Challenge page that the challenge has ended

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#283]
## Issue Context

Add a message saying the July challenge has ended, and link to the new challenge:

![image](https://user-images.githubusercontent.com/34313413/123690294-35eacc80-d822-11eb-9bba-70015603f1bf.png)

## Suggested Solution

See [December Challenge page](https://virtualcoffee.io/monthlychallenges/dec-2020/)/repo file for style and message.

**Comment by teezzan** [comment]
Hello @BekahHW, 
Kindly assign this to me. I would love to work on it.
Also, I noticed that all the challenges from Jan, 2020 don't have the alert. Should I add it to all of them? Or is there a reason why it is like that?

Thank you.

**Comment by BekahHW** [comment]
@teezzan awesome! We just never got around to adding it to the other challenges. If you're up for it, you can!
