### ISSUE TITLE
Should we upgrade to latest yarn and node version?

### ISSUE THREAD

**Issue by secondl1ght** [Virtual-Coffee/virtualcoffee.io#288]
# Should we upgrade to latest yarn and node version?
I would like to start a discussion on if we would like to upgrade the repo to the latest node.js version and yarn version. When setting up my local environment to start contributing to the project I (with the help of others) noticed that the current node version is 12 and the latest version is 16.5.0. Also the current yarn version seems to be using the older version and not the latest 
'berry'/3.0.0 version.

The node v12 doesn't seem to be a problem but I would like to highlight one issue I ran into while forking, cloning and installing the dependencies via the 'yarn' command (with yarn v3.0.0) as listed in the documentation: https://github.com/Virtual-Coffee/virtualcoffee.io/blob/fc61f7ec9589c19ba1e63d45c1c0ccc52c9b91a5/README.md#local-development

When using the latest version of yarn there are many (>700) files that get created in the ./yarn/cache directory inside the project. These files need to be added to the .gitignore file so they are not committed to the repo during development. I have included a pull request with this issue #289 that adds the files to .gitignore as recommended by the yarn docs. There are 3 other changes in that pull request: a newly created .yarnrc.yml file and changes to the yarn.lock file (all this was done by simply running the yarn command with the latest version), I also ran 'yarn set version berry' which created a .cjs file in the /releases directory.

An alternative option to merging my PR and upgrading yarn to version 3.0.0 would be to just update the local development documentation to state what yarn version should be used with the project to avoid confusion. I can volunteer to do that task if we decide to go that route.

Again the node version seems to be not an issue so that is really a separate discussion if we want to upgrade to the current version.

# Helpful Resources
This is where I pulled the .gitignore info from: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

Here is the full Yarn documentation about migrating a project from Yarn 1 to Yarn 2: https://yarnpkg.com/getting-started/migration I have not gone through everything here, I think the project maintainers who know this codebase well should probably have a look through this and see if there are any concerns. I don't know what all the new features are with the latest yarn but the developers seem to be pretty excited about it so there might be some neat stuff (it's above my level at this point).

# Collaborators 
@davidalpert helped me with this and to come to this conclusion, thanks again! I also got some help from a few other people discussing on the Slack group.

**Comment by danieltott** [comment]
@secondl1ght Thank you for this issue!

Package managers continue to be a huge pain in the behind.

My understanding previously was that using the v1 syntax would allow users using v1 _or_ v2 to run the build without any problems - but that doesn't seem to be the case. 

What I _don't_ want to happen is users that have the classic version of yarn to be unable to run this.

In fact - I am pretty sure this _shouldn't_ happen when you clone the repo and run `yarn`.

I've updated the .nvmrc file to point to node 16.

Can you try cloning the repo again fresh (from `main`) - then running `yarn` and letting me know what happens?

**Comment by nickytonline** [comment]
It's fine to update the node version, but upgrading to yarn 3 will force anyone that works on the project to use yarn 3 as the lock file format is different, so I would caution on upgrading to yarn 3 as yarn 3 will not work on a lot of other projects. For example, it currently doesn't play nice with webpack which is a lot of projects.

You can manage multiple versions of yarn, but this would potentially trip up folks who may be new to open source or contributing to the project.

**Comment by danieltott** [comment]
The hardest thing about this is that all of the docs talk about upgrading your project to `yarn 3` or `berry` or whatever - but if you just have `yarn` installed on your machine and run `yarn` inside this project, won't it use the version specified in the lockfile? I have yet to be able to replicated @secondl1ght 's issue with extra files being generated etc.

In fact, I just created a new directory, ran `yarn set version 3.x` and installed some packages. `yarn -v` returns `3.0.1-rc.2`. Then, in the same terminal, `cd`ed into the virtualcoffee.io repo, ran `yarn -v`, and it returned `1.22.11`.

So I guess my question is - if we leave yarn v1 as the yarn version that the lockfile is in, does that create issues for people? Can anyone replicate the situation @secondl1ght ran into here?

**Comment by abbeyperini** [comment]
Cloned the repo and went through the README instructions. Build ran fine and I don't see a ./yarn directory. Looks like it used yarn v1

**Comment by secondl1ght** [comment]
I just tried again, cloned a new repo and ran yarn. I get the same result, it doesn't use the version of yarn in the repo for me, it upgrades yarn to the latest version which creates all the files I talked about. Not sure if this is because I have the latest yarn installed globally, I still don't fully understand how global yarn vs project level yarn differs... it sounds like we don't want to upgrade to the latest version which is fine. But I do think we should update the documentation then and figure out how my yarn setup is causing this issue so we can explain for new users so they don't run into this problem. Because it is very confusing for someone new who is trying to contribute. I am good with troubleshooting like this but it could deter other people from trying.

This is how my environment is working: When I clone a new repo and run yarn -v I get 3.0.0, when I run yarn -v in a new terminal I get 3.0.0. I also get this message after running the yarn command, so it is able to recognize that the version of yarn in the repo is older but it automatically upgrades it. So maybe there is a yarn command flag that tells it to use the version in the repo?
```
➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍
```

**Comment by abbeyperini** [comment]
I ran npm install -g yarn and the version I get from running yarn -v in my project repo is 1.22.11

**Comment by secondl1ght** [comment]
What if you run ```yarn set version latest``` globally and then run yarn -v in your project repo?

**Comment by secondl1ght** [comment]
Maybe the old version of yarn respects the version in repos but when you install the latest version of yarn globally it tries to upgrade all repos to the latest version which causes issues?

**Comment by danieltott** [comment]
@secondl1ght did you run `yarn set version latest` inside the virtualcoffee.io repo directory? That command isn't a global command, it's a local command for the current directory...

**Comment by secondl1ght** [comment]
I have a fork of the vc repo, I made sure it was current with the main one. After that I cloned it into a new project directory, at that point I run yarn -v and get 3.0.0, so this version is set without me running the yarn set version latest command on a fresh project directory somehow.

**Comment by danieltott** [comment]
Did you install `yarn` via `npm`? if you run `npm install -g yarn` then `yarn -v` is it still 3? the [installation guide](https://yarnpkg.com/getting-started/install) states that the version should be `1.22.0` or something to start...

**Comment by secondl1ght** [comment]
Yes I installed yarn with this npm command, I just ran it again and I still get v3 after. Maybe if I removed yarn entirely then tried it would start with v1, but it seems like we need to have have yarn v1 installed globally in order to work in this repo right? Or has somebody been able to have v3 yarn installed and still use v1 yarn on the project repo? 

Like @nickytonline suggested we could ask people to do yarn version control but i'm not sure how complicated that is. I personally use the latest version of yarn for other repos, I could probablly figure out how to version control when contributing to VC. We might not have another choice? I guess I should research more on how yarn works to figure out exactly what is happening. I can also ask yarn support some questions.

**Comment by danieltott** [comment]
Yarn, according to their docs, does this automatically. There's just something breaking down in this situation and I still don't know exactly what it is.

I've updated this repo to the latest version of node - can you run `nvm use` inside the repo, then run `yarn` and see what happens? I'd also be curious about the output of `npm list -g yarn`

**Comment by secondl1ght** [comment]
Ok so I did ```nvm use``` and then ```yarn``` and it still upgraded me to the latest version of yarn. The output of ```npm list -g yarn``` is 
``` 
/home/mk/.nvm/versions/node/v16.5.0/lib
└── yarn@1.22.11
``` 
...so now I am even more confused.. lol XD.

**Comment by danieltott** [comment]
And `nvm use` and `yarn` were in a fresh copy of the repo, right? This is indeed confusing.........

**Comment by secondl1ght** [comment]
Yes that's right, if you want to do a screen share and work through it live I could do that in the co-working room. Then I can at least show you exactly what I am seeing.

**Comment by danieltott** [comment]
@secondl1ght I'm sorry I haven't had time to pair up, but nobody else is running in to this issue, so I'm going to close this for now. Maybe next week some time we can get together and see what's up!

If anyone else runs into similar issues, please feel free to drop a comment here and we can investigate more.
