### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by BryantIT** [Virtual-Coffee/virtualcoffee.io#3]
Increase accessibility on site for language support and to allow scalable zooming

![accessibilty-audit-virtual-coffee](https://user-images.githubusercontent.com/53241316/90632252-be9fe180-e1e9-11ea-82e7-be39b5585bf1.png)

**Comment by tkshill** [comment]
This is a great candidate for a first issue for a beginner, and an important one as well!

**Comment by danieltott** [comment]
@BryantIT Thank you for the issue! We've pushed out a new design that took care of these for now 💯
