### ISSUE TITLE
Should the tense be changed in Newsletter copy

### ISSUE THREAD

**Issue by ClJarvis** [Virtual-Coffee/virtualcoffee.io#308]
## Issue Context

In the newsletter section the text on index.njx reads  src>newsletter>index.njx

> Beginning in January 2021, our newsletter will include upcoming Virtual Coffee events, interesting things our members are doing, job postings we've seen, and lots more. 

The copy was written before the newsletter was a regular feature of VC. Should the text be changed to signify that the newsletter is now active?  suggest Since January 2021 our monthly newsletter includes ...

**Comment by BekahHW** [comment]
@ClJarvis Absolutely, and great catch! Do you want to take this issue?

**Comment by ClJarvis** [comment]
We can leave it for someone else like a newer member that wants an good first issue.

**Comment by ABeck617** [comment]
Hey @ClJarvis  and @BekahHW I'm a newer member and would like to take a shot at fixing this issue. I'm not sure how to assign myself this issue

**Comment by ClJarvis** [comment]
One of the maintainers will have to assign the issue.

**Comment by BekahHW** [comment]
@ABeck617 it's yours! Reach out if you have any questions or need support!

**Comment by ABeck617** [comment]
Hey @BekahHW Thanks a lot! I do have a question. So I have forked and clone the repo. After that I have made the changes on VSCode. Do I need to make a pull request to update the changes to the original repo?

**Comment by ClJarvis** [comment]
Correct, push the changes and open a pull request.  Then someone will review it.  
I don't know how familar you are with the process but checkout our [contributor guide](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/CONTRIBUTING.md#creating-a-pull-request) if you have questions.

**Comment by BekahHW** [comment]
Thanks, @ClJarvis for your help on this one!

**Comment by ABeck617** [comment]
Thanks alot @ClJarvis and @BekahHW
