### ISSUE TITLE
Add New/Prospective Member resource page

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

For people looking to join Virtual Coffee - let's have a specific page just for that, and add it to the [Member Resources](https://virtualcoffee.io/member-resources/) section.

### Proposed solution

This should have at least the following, but I'd love to hear any thoughts/additions:

- [ ] A "How do I join" section
- [ ] A FAQ about joining Virtual Coffee maybe?
- [ ] A short desc about what a person gets when they join, with some links to the Member Guide

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment]
@adiati98 You had a good start on this - would you like to take this one?

**Comment by adiati98** [comment]
@danieltott Sure! I'll take it 😊
Need some guidance though! 😄

**Comment by danieltott** [comment]
I think the best way to start would be to start with a fresh copy of the repo, then duplicate [the member guide page](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/bc1d99e472266181abbab222116d69f389eb1780/src/member-resources/guide-to-vc.njk) and start replacing the content. 

If it's easier for you to write in the first stage in a google doc (or even as a comment here!), that's perfectly fine too - you can post a link here if you'd like.

As always reach out to me here or on slack if you want ❤️

**Comment by adiati98** [comment]
Thanks, @danieltott !
I think I'll review & fix the Google Docs as first stage since I already have the draft there 😊

**Comment by adiati98** [comment]
@danieltott Here's the Google Docs version of [Guide For Prospective VC Members](https://docs.google.com/document/d/17kYKUa-ziWEvfANZXzXRtE3259SofaAS1-DyREjDbFU/edit).
I open it for editing, so feel free to edit or add anything.

I will start to draft it in .njk tomorrow while waiting for any changes.

Thanks! 😄

**Comment by pedaars** [comment]
Hi, I added a few words hopefully it is helpful.

**Comment by danieltott** [comment]
@adiati98 let me know when/if you start working on this. I just pushed up some changes to the site that should make it much easier to make these additions. I haven't had time to update any documentation yet - but I converted the [guide page to markdown](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/member-resources/guide-to-vc.md)

This should make it a lot easier to make these content pages from here on out. Let's pair up if you'd like!

**Comment by adiati98** [comment]
@danieltott I can pair today in 1 or 2 hours from now if you're up to it!

**Comment by danieltott** [comment]
@adiati98 reach out when you're available - I may be around or if not we can try tomorrow!

**Comment by adiati98** [comment]
@danieltott I'm ready if you are! 😉

**Comment by adiati98** [comment]
> Hi, I added a few words hopefully it is helpful.

Thanks, @pedaars!

**Comment by danieltott** [comment]
closed in #336
