### ISSUE TITLE
Install and Run link in CONTRIBUTING.md goes nowhere 

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/virtualcoffee.io#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the [Table of Contents section in CONTRIBUTING.md](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/CONTRIBUTING.md#table-of-contents), the link to "Install and Run" (see attached screenshot) goes nowhere.
It's because that link changed to "[Local development](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/CONTRIBUTING.md#local-development)".

This would be a good first issue for those who start to get their hands wet in open source!

<hr/>

![table-of-contents](https://user-images.githubusercontent.com/45172775/132096902-74c3c6fa-e528-454a-b38e-c4aa00027cc0.jpg)

### Environment

```markdown
- OS:
- Node:
- yarn:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue.!

**Comment by danieltott** [comment]
Hey @himanshu007-creator - thanks for the message! We're trying to reserve the `good first issue` issues for contributors who don't have very much open source experience as a way to help them get started. I appreciate your enthusiasm though - we'll probably have a decent number of issues that fit the bill over the next month or two 🙌

**Comment by himanshu007-creator** [comment]
Got it🙌🏽

**Comment by demonicirfan** [comment]
Hi, I have never done an open-source contribution, I would like to start with this one, can I 😊

**Comment by danieltott** [comment]
Hey @demonicirfan - thanks for the message! We're trying to reserve the good first issue issues for contributors who don't have very much open source experience as a way to help them get started. I appreciate your enthusiasm though - we'll probably have a decent number of issues that fit the bill over the next month or two 🙌

**Comment by EbonyLouis** [comment]
Hi, I've never worked on open source and I would love to start... could I work on this issue?

**Comment by danieltott** [comment]
@EbonyLouis its all you!

**Comment by EbonyLouis** [comment]
@danieltott Thank you!
