### ISSUE TITLE
Member Website Link Invalid URL

### ISSUE THREAD

**Issue by brandonbrown4792** [Virtual-Coffee/virtualcoffee.io#32]
## Describe the bug

On the members page (https://virtualcoffee.io/members/), if the GitHub user does not include http:// or https:// in their GitHub website link, a new tag is opened with the path appended to the virtual coffee URL instead of the GitHub website link.

## To Reproduce

1. Go to https://virtualcoffee.io/members/
2. Click on Suraj Panchal's name or website link
3. See error (404 page for virtual coffee)

## Expected behavior

Should open to Suraj's website and not to a link in virtual coffee's website.

## Screenshots

![image](https://user-images.githubusercontent.com/42486126/94854227-974c4f00-03fa-11eb-9e0e-e0e3570487fc.png)

## Desktop (please complete the following information):

- OS: MacOS Catalina
 - Chrome
 - Version 85.0.4183.121

**Comment by BekahHW** [comment]
Thanks @brandonbrown4792. Looking at this now.

**Comment by danieltott** [comment]
I think we could do at least a rudimentary fix for this where we check if the url starts with http and pre-pend it if not.

I could see this being in either the data js file or the members.njk file

**Comment by mrsantons** [comment]
Could I nab this?

**Comment by danieltott** [comment]
@mrsantons It's all you!

**Comment by danieltott** [comment]
![alright-hey-ya](https://user-images.githubusercontent.com/360261/95115246-27e4a100-0713-11eb-8715-52029456f47e.gif)

**Comment by danieltott** [comment]
Thanks @brandonbrown4792 and @mrsantons !!!
