### ISSUE TITLE
Add more thorough description to monthly challenge page

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

It would be nice to have a clearer description on the [Monthly Challenges](https://virtualcoffee.io/monthlychallenges/) page. 

### Proposed solution

If we're thinking about it in terms of non-members, let's give them a glimpse into what monthly challenges are, how folks can participate, and include our Project Leads.  

The goal is to allow everyone at every stage to participate and to make sure that everyone knows there is support at whatever stage you are. 

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by jdwilkin4** [comment]
Hi there! I am interested in working on this issue.

**Comment by danieltott** [comment]
@jdwilkin4 it's all you!

**Comment by jdwilkin4** [comment]
I tried to incorporate all of @BekahHW 's suggestions into the updated monthly challenge page with my PR.
