### ISSUE TITLE
Add 'How to write a Good Issue' guide to Member Resources

### ISSUE THREAD

**Issue by YolandaHaynes** [Virtual-Coffee/virtualcoffee.io#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Context for documentation change

There is no guide/documentation in the repo.

### Proposed solution

Providing a guide/documentation on writing a good issue. This helps contributors on how to write a good issue, and it can benefit the maintainers by keeping track of all the tasks that need to be done in a GitHub repository.

There is a [guide pinned in the #monthly-challenge](https://virtual-coffee-group.slack.com/archives/C01DYTKRYAY/p1630959322039400) channel about how to write a good issue that can be used.

For the repo, the guide can be stored in the CONTRIBUTING.md, possibly after the working with issues section. Also, I think it can live in the src> member-resources > as a new file like "guide-to-write-good-issues.md"

### Resources that can help

- [GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue)

- [GitLab](https://docs.gitlab.com/ee/user/project/issues/)

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by BekahHW** [comment]
@YolandaHaynes this is great! This lets us know that we definitely don't have a resource for it. And I appreciate that you have a good reason for it. 

Do you think the site would be a good place for it? I might call it a feature if that's what you're thinking. 

Can you add just a couple of things:

1.  Link to the pinned issue guide in slack monthly challenge channel 
2. Suggest where to put it in the repo file structure. (Take a look at the new guide for members. I would bet adding it there or somewhere in there would work).

**Comment by YolandaHaynes** [comment]
Hi @BekahHW , I have made the changes by adding the pinned guide and my suggestions where I think the guide can live in. 

The site can be a good place for it! So my thought process was that "the writing a good issue guide" can be inserted inside the CONTRIBUTING.md, so a member can access it in one [area](https://virtualcoffee.io/member-resources/guide-to-vc/#contributing-to-virtual-coffee) on the website. However, I am open to any suggestions! 

How can I change the label or add the label of 'new feature'. Would appreciate the guidance. Thank you!

**Comment by danieltott** [comment]
Hey @YolandaHaynes !

I am not 100% sure where you left this with @BekahHW but I think it would be great to add this as a page to the Member Resources section. You can copy the existing guide to member center markdown file as a start!

I love the idea of adding a link to this new page on contributing though 💯

**Comment by danieltott** [comment]
@YolandaHaynes thanks again for getting this started! Would you like to do this one? I'd be happy to pair up if so - let me know!

**Comment by aurelieverrot** [comment]
Can we add the Maintainer Guide, and Maintainer Checklist as well in the same section?

**Comment by adiati98** [comment]
@danieltott @BekahHW would it be more organized if we create like a main `<li>` in the Maintainer Guide to compile and keep "How To Write Good Issues", "Maintainer Checklist", and any other open source guides, in one place?

Something like:

- Guide To Open Source Contributions 
  - How To Write Good Issue
  - Maintainer Guide
  - Maintenance Checklist
  - ...
- Guide To Virtual Coffee 
- ...

**Comment by danieltott** [comment]
@aurelieverrot @adiati98 absolutely we want all of these resources here! Ayu that's a great idea for the future - to keep it simple right now let's go ahead with individual separate pages inside the resources section. We'll figure out a good solution for subsections once we have all of these in here!

**Comment by adiati98** [comment]
Sounds great, @danieltott 😊

**Comment by YolandaHaynes** [comment]
@danieltott I would love to pair up and tackle this!

**Comment by BekahHW** [comment]
@YolandaHaynes how's this going? Let me know if you want to pair up this week!

**Comment by YolandaHaynes** [comment]
@BekahHW Thanks for the offer! So far I'm good. I was able to meet up and pair with @danieltott late last week! Sorry for the delay. I thought I had time over the weekend, but it didn't pan out as I hoped. I'm hoping to finish this ASAP!

**Comment by danieltott** [comment]
closed in #349 !!
