### ISSUE TITLE
Add Oct. Monthly Challenge Page

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#345]
## Issue Context

Add October Challenge to the Site

## Steps

- [ ] Add folder src > monthlychallenges > Oct-2021
- [ ] Add index.njk to the file
- [ ] Using [June 2021](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/monthlychallenges/june-2021/index.njk) as kind of a template, create October 2021 
     - [ ] Give description for the challenge and steps to participate
     - [ ]  Include a link to Digital Ocean's Hacktoberfest page
     - [ ] Add a Resources section that links to most recent YouTube Videos and any guides you think would be useful
     - [ ] Add info about Hacktoberfest Co-working room (details tba)
     - [ ] Add section with a list of VC-Approved repositories.
- [ ] Create a PR that uses `closes #{number of this isse}`
- [ ] Request me to review PR once ready.

**Comment by aurelieverrot** [comment]
I take it :)
