### ISSUE TITLE
Add end of challenge message to Sept Challenge

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#346]
## Issue Context

Add a message saying the Sept challenge has ended, and link to the new challenge:

![image](https://user-images.githubusercontent.com/34313413/123690294-35eacc80-d822-11eb-9bba-70015603f1bf.png)

## Suggested Solution

See [December Challenge page](https://virtualcoffee.io/monthlychallenges/dec-2020/)/repo file for style and message.

**Comment by jdwilkin4** [comment]
Hi there! I would like to work on this issue if it is still available. 
Thanks!

**Comment by danieltott** [comment]
@jdwilkin4 you got it!
