### ISSUE TITLE
Create auto-generated Social Cards

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

A great feature to have on the site is automatically-generated social image cards. Social image cards are what you see when you share a site in slack/twitter/facebook etc. Our current card is the same for every page:

![default social card](https://github.com/Virtual-Coffee/virtualcoffee.io/raw/main/src/assets/images/vc-social-card.png)

However it's possible to create cards that have the page title/description on them, things like that. This would be a killer improvement to the site!

Here's an example of a social card for a GitHub Issue:

![image](https://user-images.githubusercontent.com/360261/135634770-3dfa8ce0-54cc-45d8-ab1f-eff47277d95d.png)

As you can see, there's the title and some other interesting information - pretty cool!

### Proposed solution

The idea here will be to create the social image _as a web page_, and then have eleventy screenshot them for each page. This allows us to use our css/styles for everything, and even to design different layouts for different sections if we wanted!

The first step here will be to design a nice-looking default template that includes a title, description, and the VC logo at the top.

Then we can hook up 11ty to create images for each of them.

Here are some posts that used the same strategy:
- [Generating Social Sharing Images In Eleventy](https://www.stevenhicks.me/blog/2020/12/generating-social-sharing-images-in-eleventy/)
- [How to automatically generate social sharing images for Eleventy](https://mtm.dev/eleventy-social-sharing-images)

### Alternatives Considered

Another possibility would be to use [imgix](http://imgix.com/) to layer images/text, but we lose some control there and don't get to use our fonts as easily. [Here's a post following a similar strategy](https://www.stevenhicks.me/blog/2020/12/generating-social-sharing-images-in-eleventy/) (except they used cloudinary). I think the main solution gives us a lot more flexibility.

### Additional Resources

This will probably entail a lot of back-and-forth to get the design and settings right, so only take this on if you're willing to give it some time. It's not at all a rush though, so it doesn't need to be a ton of time all at once!

I'd also be really happy to pair up with anyone who's interested in this one.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by jenkens-dev** [comment]
Hey Dan, I'd love to work on this issue if it's available. I just recently did something similar for my digital garden with Gatsby and Cloudinary but I'm sure after reading the resources I could figure it out with Eleventy.

**Comment by danieltott** [comment]
@jenkens-dev That'd be great!

**Comment by BekahHW** [comment]
Hey @jenkens-dev I wanted to check-in and see if you needed any support. Let me know 🙂

**Comment by jenkens-dev** [comment]
Hi @BekahHW thanks for reaching out! This issue is a bit harder than I initially realized and I have less time than I thought. If this is a priority task or someone else is interested in tackling it feel free to re-assign it. Otherwise, I'd love to still try my hand at it.

**Comment by danieltott** [comment]
Hey @jenkens-dev - with the move to Remix (#545) we're going to go in a different route here 👍
