### ISSUE TITLE
README link broken in Members issue

### ISSUE THREAD

**Issue by torianne02** [Virtual-Coffee/virtualcoffee.io#38]
## Describe the bug

On issue #13 there is a link to the README with instructions to get the site running locally. This link is broken. 
- link is currently: https://github.com/Virtual-Coffee/virtualcoffee.io/issues/README.md#local-development

## To Reproduce

1. Go to issue #13 
2. Scroll down to `How to add yourself` section
3. Click on `Local Development steps listed in our README` link

## Expected behavior

This link should direct the user to README#local-development

## Screenshots

(If applicable, add screenshots to help explain your problem.)

## Desktop (please complete the following information):

- OS: macOS 10.15.6
 - Browser: chrome
 - Version: 85.0.4183.121

## Additional context

- I did not include the proper URL for the purpose of allowing someone to explore and find it themselves. 

Happy Coding 🎃

**Comment by danieltott** [comment]
Really thought you could do relative links in GitHub markdown 😡

**Comment by MikeRogers0** [comment]
@danieltott I think you can, it just needs to use the full url:

[Local Development steps listed in our README](https://github.com/Virtual-Coffee/virtualcoffee.io/#local-development)

**Comment by danieltott** [comment]
@MikeRogers0 That definitely works, but only for the README - the thing I was trying to pull off was a link that would link to a markdown file in the repo, and like automatically point to the file in the default branch. We have the same problem with the link to CONTRIBUTING. I think this works _in markdown files in the repo_, but not in issues.

Thanks for the help @MikeRogers0 and @torianne02 !
