### ISSUE TITLE
Add end of challenge message to August challenge

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#387]
## Issue Context

We missed adding this one in early September, but let's update that now.

Add a message saying the August challenge has ended, and link to the new challenge:

![image](https://user-images.githubusercontent.com/34313413/123690294-35eacc80-d822-11eb-9bba-70015603f1bf.png)

## Suggested Solution

See [December Challenge page](https://virtualcoffee.io/monthlychallenges/dec-2020/)/repo file for style and message.

**Comment by adiati98** [comment]
Hey @BekahHW,
Can I grab this one?

**Comment by redapy** [comment]
can I take this ?

**Comment by danieltott** [comment]
@redapy you got it!
