### ISSUE TITLE
Member bio taking up too much space

### ISSUE THREAD

**Issue by MattyMc** [Virtual-Coffee/virtualcoffee.io#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Members can write their biographies (e.x. in `mattymc.js`), but since there's no character limit on the bio it can result in one member have a huge vertical height. 

The bio added in #383 is a good example. Let's remove this one for the time being.

### Desired fix:

- [x] Immediately comment out the long bio.

### Steps To Reproduce

1. Open any member bio in `_data/members/`.
2. Add a large amount of markdown to the `bio` property.
3. Visit the members page.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Environment

```markdown
- OS:
- Node:
- yarn:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by MattyMc** [comment]
I'll take this on: 

1. Immediately comment out the long bio. 
2. Add a note in the example bio to limit length.
3. Figure out a longer term solution to prevent problem automatically in future.

**Comment by danieltott** [comment]
@MattyMc I updated this issue to be more specifically about the short-term fix, and we can open a new issue addressing the general improvements to the system 👍

**Comment by danieltott** [comment]
closed via #397
