### ISSUE TITLE
Fix invalid HTML generated by various `.njk` files

### ISSUE THREAD

**Issue by MattyMc** [Virtual-Coffee/virtualcoffee.io#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The `.njk` files used to generate the HTML pages contain errors, such as improper nesting and unclosed tags. These may cause unexpected behaviour and rendering in the browser. 

### Example of a nesting error
![image](https://user-images.githubusercontent.com/1302166/135924829-065b41a9-b6a9-4d2c-9fc5-fd3c0010dabd.png)

### Example of an unclosed tag
![image](https://user-images.githubusercontent.com/1302166/135924885-e013facb-2841-41b3-bc01-1ade96ef510d.png)

### Steps To Reproduce

1. Pull master branch down locally. 
2. `yarn start` to build site locally. This will create the .`html` files in /_site.
3. Jump into `.prettierignore` and comment out the line that ignores the files in `/_site`.
4. From the command line, run prettier: `npx prettier --check .`. This will produce a number of errors similar to the above.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Environment

```markdown
- OS:
- Node:
- yarn:
```

### Suggested Fix

- [ ] Build site, lint the constructed HTML files to surface errors.
- [ ] Fix the corresponding `.njk` files.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by MattyMc** [comment]
I'd like to take this one on. I have my code linting all setup from the other PR I was working on. Should be fast.

**Comment by danieltott** [comment]
![its all you](https://media.tenor.co/images/8494fc2ade3d9464add6d9458631a740/tenor.gif)
