### ISSUE TITLE
How to ask for help with code Member Resource

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#417]
### Issue Context

We now have a [Member Resources section](https://virtualcoffee.io/resources/) on the site. This would be a great place to add two things: a developer Resources page that links to a section on how to ask for help with your code. 

### Proposed solution
- [ ] Add a new folder in resources called `dev`
- [ ] In that folder add an index.md file for `Developer Resources`. (You can check the [virtual-coffee index](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/resources/virtual-coffee/index.md) for an idea of how to do it with updated content for this section.
- [ ] Add a `Guide to Asking Questions about Your Code` page called `coding-questions-guide.md`. You can look at [the guide to VC](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/resources/virtual-coffee/guide-to-vc.md) as an example.
     - Use the replies to [discussion 409](https://github.com/Virtual-Coffee/virtualcoffee.io/discussions/409), to create the guide.
     - Sections should include `Before asking for help`, `When asking for help`, `Specific to Virtual Coffee`. (Feel free to retitle those, but the content should reflect that, unless you have suggestions for a different organization.

**Comment by YolandaHaynes** [comment]
Hi! I would like to contribute to this one.

**Comment by danieltott** [comment]
@YolandaHaynes it's all you!

**Comment by BekahHW** [comment]
@YolandaHaynes I wanted to check in and see how this is going. Let me know if you need help!

**Comment by adiati98** [comment]
Hey @BekahHW & @danieltott,
As per Slack convo, I will take this issue 😊
Can you please assign me? Thanks!

**Comment by jeremiahlukus** [comment]
Hey when I was still in college someone sent me this when I asked them a question over email. It has been a big help to me and maybe you can copy some information from it

https://docs.google.com/document/d/1prD4Yj-9BsThKFgS2FTd0UHADXt0Ivhb7Ai9sJikgfc/edit

**Comment by danieltott** [comment]
Live via #549
