### ISSUE TITLE
Add Virtual Coffee logo as favicon to webpage

### ISSUE THREAD

**Issue by clandau** [Virtual-Coffee/virtualcoffee.io#42]
## Issue Context

It would be cute to have the VC image as the favicon image on the website. 

## Suggested Solution

Possible steps:
1. Create favicon.ico image file of the VC logo, in `src/assets/images`
2. add to head tag of main `index` file

## Additional Resources

[MDN - Adding_custom_icons_to_your_site](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Adding_custom_icons_to_your_site)

**Comment by ClJarvis** [comment]
Is this still open? I'd like to do if it's not claimed yet.

**Comment by danieltott** [comment]
It's all you @ClJarvis ! Thank you!

**Comment by ClJarvis** [comment]
I'm attempting to push up a change. I have a warning that the index.html is in the gitignore. Do use -f I submit anyway?
 I linked to the favicon in the head of index.html  _site/index.html

**Comment by danieltott** [comment]
@ClJarvis This site uses eleventy to build the site from templates found in `src` - one effect of this is that all of the files in `_site` will be overwritten every time we build via `start` or `build`. 

So! Instead, you'll want to make the change in the layout template, which can be found in `src/_includes/layouts/base.njk`

If you've run `npm run start` to get the site running locally, changes to `base.njk` should result in the site rebuilding!

Hopefully this helps.

**Comment by ClJarvis** [comment]
@danieltott  Thank you.  I have made corrections and will make a pull request shortly.

**Comment by danieltott** [comment]
closed via #43 thank you @ClJarvis and @clandau !
