### ISSUE TITLE
Improve focus styles

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

We're using some default bootstrap focus styles and they're pretty minimal. It would be great to have much more obvious focus styles.

![image](https://user-images.githubusercontent.com/360261/137198080-33cb3fbf-6e09-4a18-bfd5-ce385a412776.png)

### Proposed solution

Maybe a nice 2px outline in our pink or orange?

We'll need focus styles for:
- [ ] The top nav
- [ ] The `smallhomepageblocks` nav
- [ ] Inline links throughout the site
- [ ] Any buttons / button-style links

### Alternatives Considered

I'm open to other design suggestions for sure.

### Additional Resources

https://dockyard.com/blog/2020/04/28/designing-for-accessibility-focus-states

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by colabottles** [comment]
I'll take this one.
