### ISSUE TITLE
Different label for hireable flag on members

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#48]
## Describe the bug

On the members page, if the member has a website, the label says “available for work” and if not the label says “hireable”

## To Reproduce

1. Go to https://virtualcoffee.io/members/

## Expected behavior

They should say the same thing

**Comment by brandonbrown4792** [comment]
Could I try and tackle this one?

**Comment by danieltott** [comment]
@brandonbrown4792 It's all you!

**Comment by danieltott** [comment]
Fixed via #51 - thanks @brandonbrown4792!
