### ISSUE TITLE
Edit podcasts' transcriptions

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/virtualcoffee.io#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

Edit/Clarification on existing content

### Context for content change

I noticed that our podcast episodes have automatically generated transcriptions.
There are typos in every episode.  

### Proposed solution

To make it more accessible, we can manually edit the transcriptions based on the W3C guidance for [transcribing audio to text](https://www.w3.org/WAI/media/av/transcribing/).

### Resources that can help

https://www.w3.org/WAI/media/av/transcribing/

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by adiati98** [comment]
Hi @danieltott, I had experience in fixing transcriptions for podcasts before for [Software Engineering Unlocked ](https://github.com/mgreiler/se-unlocked) podcast.
Outside the W3C, they do have [their own guidance](https://github.com/mgreiler/se-unlocked/blob/master/Transcription_Guidelines.md) as well to transcribe their podcast which I find neat.

This would be a very long work, but I can do it little by little if it's approved 😊
Otherwise, feel free to close this issue 😄

Thank you!

**Comment by danieltott** [comment]
Hey @adiati98 

I've created this repo with the current transcripts: https://github.com/Virtual-Coffee/podcast-transcripts

They're all in .srt files

Fixing typos and small changes are perfectly possible by hand-editing these. If we need to make larger changes, we'll have to figure something else out.

Feel free to start on one though and we can see how it goes!

Once you are finished with one, I can update the transcript on our podcast hosting platform.

If this is too fussy or annoying, don't worry about it, and we can figure something else out in the future...

**Comment by adiati98** [comment]
Thanks, @danieltott !
Let me try and see how it goes! 😀

**Comment by adiati98** [comment]
We now have the [podcast-transcripts](https://github.com/Virtual-Coffee/podcast-transcripts) repo to close this issue.
