### ISSUE TITLE
The link of Code of Conduct and Our Members navigate to About Virtual Coffee page 

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/virtualcoffee.io#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Both links to Code of Conduct and Our Members navigate to About Virtual Coffee page.

### Steps To Reproduce

1. On [Virtual Coffee homepage](https://virtualcoffee.io/) go to All Things Virtual Coffee section (as pics attached)
2. Click on the Code of Conduct link, and/or
3. Click on the Our Members link

![vc-web-links](https://user-images.githubusercontent.com/45172775/147126197-6e05713a-1f9b-482e-987b-e23f705fe013.jpg)

 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Environment

```markdown
- OS:
- Node:
- yarn:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by adiati98** [comment]
@danieltott can you assign me?
I will fix this 😊
Thank you 😄

**Comment by danieltott** [comment]
Thanks @adiati98 !
