### ISSUE TITLE
Add January Challenge to site

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#499]
We're moving on from Creative Community and onto Month of Learning. 

 ## Issue Context

Add January Challenge to the Site

## Steps

- [ ] Add folder src > monthlychallenges > Jan-2022
- [ ] Add index.njk to the file
- [ ] Using [June 2021](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/monthlychallenges/june-2021/index.njk) as kind of a template, create January 2022
- [ ] Create a PR that uses `closes #{number of this isse}`
- [ ] Request me to review PR once ready.

We need to get our new challenge up on the site. You can refer to [last year's challenge](https://virtualcoffee.io/monthlychallenges/jan-2021/), although we have some updates:

1. We're not recording resources on the site. Instead we have [a discussion](https://github.com/Virtual-Coffee/virtualcoffee.io/discussions/496)
2. We have #learning-together channel in slack if you're looking for a study buddy or someone to learn along with. 
3. We want to add [this info](https://github.com/Virtual-Coffee/virtualcoffee.io/discussions/493) in some form to the site either as a linked resource or within the challenge.
4. We need to set a goal for the challenge.

**Comment by Andrew-Bush** [comment]
Dibs 👋

**Comment by BekahHW** [comment]
Thanks, @Andrew-Bush!!!
