### ISSUE TITLE
Create an Events Page

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#5]
-Using https://meetingplace.io/api, show upcoming events.
-Add a link to sign-up page https://meetingplace.io/virtual-coffee

**Comment by saramccombs** [comment]
Literally just thought about this issue and came here to see if already existed as an issue.. and was reminded that it did. ❤️ Brain no good right now.

**Comment by clandau** [comment]
I'll pick this up. OR if someone newer wants to work on this with my help, even better!

**Comment by BekahHW** [comment]
@clandau that would be awesome! I'm not positive here, but I think you could start by adding src > events.njk with layout: layouts/home.njk, and then go from there. But also, @danieltott is the wizard here.

**Comment by andreamartz** [comment]
Courtney,
I'm happy to work on this with you.

Andrea

**Comment by clandau** [comment]
yes! you can reassign to @andreamartz ! We'll be meeting to figure this out.

**Comment by danieltott** [comment]
This is awesome! I'd be happy to do a quick zoom or something but wouldn't be able to until Monday. If you're working in the meantime on this please don't hesitate to ask questions here or in slack

**Comment by danieltott** [comment]
Awesome first version of Events is merged and live via #56! Thank you @andreamartz and @clandau!!!

![](https://media1.giphy.com/media/mXnO9IiWWarkI/giphy.gif)
