### ISSUE TITLE
February Challenge: Pairing

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#511]
We're moving on from Creative Community and onto Month of Pairing. 

 ## Issue Context

Add February Challenge to the Site

## Steps

- [ ] Add folder src > monthlychallenges > Feb-2022
- [ ] Add index.njk to the file
- [ ] Using [June 2021](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/monthlychallenges/june-2021/index.njk) as kind of a template, create Feb 2022
- [ ] Create a PR that uses `closes #{number of this isse}`
- [ ] Request me to review PR once ready.

We need to get our new challenge up on the site. You can refer to [last year's challenge](https://virtualcoffee.io/monthlychallenges/dec-2020/), although we have some updates:

1. We have #learning-together channel in slack if you're looking for a study buddy or for 1:1 help they can head to #help-and-pairing. 
2. We want to add [this info](https://github.com/Virtual-Coffee/virtualcoffee.io/discussions/493) in some form to the site either as a linked resource or within the challenge.
3. We need to set a goal for the challenge.

**Comment by redapy** [comment]
I can take this

**Comment by redapy** [comment]
I'm trying to combine the [June 2021](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/monthlychallenges/june-2021/index.njk) template with the [last year's challenge](https://virtualcoffee.io/monthlychallenges/dec-2020/) content. But, I can't find a theme or a goal for the challenge. Should I wait until we set a goal, or just skip that part for now?
One more question, should I include the tables (empty)?

**Comment by BekahHW** [comment]
Hey Reda! I would skip theme for now and leave off the table until we get some feedback. 

Maybe @danieltott had thought here too.
