### ISSUE TITLE
Add team members

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

Edit/Clarification on existing content

### URL of existing page

https://virtualcoffee.io/members/

### Context for content change

Right now only the maintainers have teams on their member cards. I'd like to see _all_ of our teams represented!

### Proposed solution

This can be done by adding team members to the [teams.json](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/_data/members/teams.json) file:

https://github.com/Virtual-Coffee/virtualcoffee.io/blob/c4dd5d4696561386562daff27245440ccd0433cf/src/_data/members/teams.json#L1-L7

So for a new team, add an entry to the array, and list the users' github usernames. For example, to add @BogDAAAMN to a team called "Audio/Visual":

```diff
[
  { "name": "Org Maintainer", "members": ["bekahhw", "danieltott"] },
  {
    "name": "Community Maintainer",
    "members": ["bekahhw", "saramccombs", "tkshill"]
-  }
+  },
+  {
+    "name": "Audio/Visual",
+    "members": ["BogDAAAMN"]
+  }
]
```

### Resources that can help

We'll need a full list of team members.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by BogDAAAMN** [comment]
@danieltott are you working on this? I have time to reach out to teams and members to compile a list of teams if you don't have it

**Comment by danieltott** [comment]
@BogDAAAMN Yep it's pretty much ready to roll in #554 - feel free to check that out and let me know if there are any changes!

**Comment by BogDAAAMN** [comment]
Eyy no, looking very good!!

**Comment by BogDAAAMN** [comment]
Is it worth mentioning it in the docs of #13?

**Comment by danieltott** [comment]
@BogDAAAMN good question - I think no, just because new members probably won't be on teams yet, but I'm open to being convinced otherwise

**Comment by BogDAAAMN** [comment]
Oh yeah, that's fair 👍🏼
