### ISSUE TITLE
Longer links on members page overflowing container

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#55]
## Describe the bug

This is most noticeable in iOS (safari/firefox). When a member's link is too long, it overflows the container and causes horizontal scrolling.

## To Reproduce

In iOS Safari, or Chrome responsive mode with iPhone X selected, go to https://virtualcoffee.io/members/ and scroll down until you see an overflowed link - there are several. I think Aurelie's is the first one currently.

## Expected behavior

The link text should be truncated if it is too long for the container. This can be done with CSS - and luckily Bootstrap already has a solution for us: https://getbootstrap.com/docs/4.5/utilities/text/#text-wrapping-and-overflow

That `text-truncate` class should take care of the issue for us!

The bootstrap docs have a note about block-level elements and inline elements - we'll probably want to [make that link a block-level element](https://getbootstrap.com/docs/4.5/utilities/display/) as well so that the truncation works. 

## Screenshots
Overflowing behavior:
![image](https://user-images.githubusercontent.com/360261/95874492-eec5b580-0d3e-11eb-9d6b-b465e20dc95b.png)

After truncating the text:
![image](https://user-images.githubusercontent.com/360261/95874444-e5d4e400-0d3e-11eb-8903-0170b1147515.png)

**Comment by Cerchie** [comment]
I'd love to work on this one! I've been looking to improve my CSS skills, thanks for providing the resource to read.

**Comment by danieltott** [comment]
@Cerchie It's all you 🙌  Let me know if I can help!

**Comment by danieltott** [comment]
Closed via #57 - Thanks @Cerchie!!!!
