### ISSUE TITLE
Change "Join Virtual Coffee" section

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/virtualcoffee.io#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

Edit/Clarification on existing content

### URL of existing page

https://virtualcoffee.io/resources/virtual-coffee/join-virtual-coffee

### Context for content change

As we are pausing our membership for Virtual Coffee, we need to update the page.

### Proposed solution

There are a couple of ways that I can propose:
- Change the content of the [How can I join Virtual Coffee?](https://virtualcoffee.io/resources/virtual-coffee/join-virtual-coffee#how-can-i-join-virtual-coffee) section into some sort of announcement like "We are currently pausing our membership ..." and leave the rest of the sections as it is.
- Create a new file with an announcement of pausing the membership and provide links to our Guide To Virtual Coffee for members as a sneak peek for non-members, along with our newsletter, Twitter, and email for the public to keep in touch with us.  

### Collaborators

@danieltott & @BekahHW, any thoughts?

I will take this issue after confirmation and get assigned to me.
Thank you 😊

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment]
@adiati98 great call. I'd like to see basically the existing page stay as is, except the intro section at the top changed to have the "we are currently pausing membership" content.

![Image 2022-04-25 at 10 32 48 AM](https://user-images.githubusercontent.com/360261/165110978-b548e41f-c9f6-48d1-a1a4-801ce08c973e.jpg)

**Comment by adiati98** [comment]
@danieltott just to confirm, so we want to only change the intro?
And leave everything as it is?
