### ISSUE TITLE
Add May 2022 newsletter to site

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/virtualcoffee.io#575]
## Issue Context

Every month, we try to get the newsletter up on the site within a week of sending it out. Currently, we're moving them over "by hand."

## Steps to update

In the code base, navigate to `src > newsletter > issues` and create a new file `2022-05.jsx`.
You can look at the existing newsletters ( `src > newsletter > issues`) as a kind of template.

Make sure to add it to the index by following the steps in [Newsletters section in our README](https://github.com/Virtual-Coffee/virtualcoffee.io#newsletters) and update the content accordingly based on our email newsletter.

If you have questions, please let us know. We're up for pairing if anyone wants to walk through this!

**Comment by adiati98** [comment]
Hi @danieltott,
Would you please assign me? I'll work on this issue 😊
Thanks!

**Comment by danieltott** [comment]
Closed via #576
