### ISSUE TITLE
Content of Luxon datetime format not matching from server to client

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We use [Luxon to format time](https://moment.github.io/luxon/#/formatting) on the [events page](https://virtualcoffee.io/events). We're using the `fff` formatting option, which is a shortcut for "verbose localized date and time." 

Localized date means that javascript will use the language of the user (or at least the user's computer) when generating the date string. So, in my browser, it says "May 23, 2022 at 4:00 PM EDT"

The problem is that this content is generated on the server first, then hydrated to react by Remix. So the computer that serves the code (a server at Netlify in this case) could have a different locale specified than mine. When hydrating components, React expects the content generated by the server to match the content that React generates on the client side. When they don't match, React throws a warning in the console:

```
Warning: Text content did not match. Server: "Monday, May 23, 2022, 4:00 PM EDT" Client: "Monday, May 23, 2022 at 4:00 PM EDT"
```

We definitely want a string there on the server side, but there's no way for the server to predict what to match it to. So I think the best solution will be to have react _change_ it to the local locale after the page has loaded.

### Steps To Reproduce

This warning is hidden in production, so you'll have to run it locally to see it. Run the local server, then go to `/events` with the console open.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by JoeKarow** [comment]
<img src="https://media1.giphy.com/media/74ZOAgI9Al0Dm/giphy.gif"/>
