### ISSUE TITLE
Create a Community Page

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#6]
That's it.

**Comment by danieltott** [comment]
@BekahHW This is different than Members, right? Or is this the same?

**Comment by BekahHW** [comment]
@danieltott the idea was to have a page to promote what our members are doing. Blogs, YouTube channels, etc. But we can put it on hold if that makes sense.

**Comment by danieltott** [comment]
No no no! That would be awesome. I just wanted to check.

**Comment by anatighe** [comment]
What's the blocking issue? Does it need design?

**Comment by danieltott** [comment]
@anatighe Yeah we just don't know what's going to go on it yet so I don't want to have anyone really get rolling. Would love to use this issue to collect ideas and brainstorm though - if you have any thoughts we'd love to hear them!

**Comment by anatighe** [comment]
Cool! I guess my first thoughts are:
Who are the people using it and what's the best way to organize the info for them? Or can we add sorting/filters to meet a few different needs?
Is it mostly for community members who just want to see what other people are up to? Or should there be a way to start discussions there and ask questions?
Is it self-curated: do we need a form to let people submit?
