### ISSUE TITLE
Show the information you submitted in membership-thankyou/ page

### ISSUE THREAD

**Issue by Rafi993** [Virtual-Coffee/virtualcoffee.io#60]
## Issue Context

I just filled out the form to be added as member and after I clicked submit I think I had a doubt if I entered the correct github username and other details and there was no way to for me to verify it

## Suggested Solution

Show the details you submitted in the form in **membership-thankyou/** page

## Alternatives Considered

Mail could also be sent to the user with the details they entered

**Comment by danieltott** [comment]
@Rafi993 Thank you for the issue! 

Currently, there's no easy way to pull this off. This form is submitted via Netlify forms, and the thank you page is a static page that doesn't receive any data from Netlify Forms. So I think in the current setup we'll have to reach for some javascript. I'm certainly open to suggestions!

**Comment by Rafi993** [comment]
I think it is possible to send email when user submits the form https://docs.netlify.com/forms/notifications/ but I don't know if the email can contain submitted data.

**Comment by danieltott** [comment]
Yeah - that feature is nice but is more of a notification for us with a dump of the form data than a nice-looking response to the user. 

In the future we definitely have plans to hook up a nice automated thank-you message via webhooks/zapier - still working on that!

**Comment by SNikhill** [comment]
Can I be of assistance in any way?

**Comment by danieltott** [comment]
This form is going away, so this won't be an issue any more. Thanks for your input @Rafi993 !
