### ISSUE TITLE
Typesafe GraphQL client

### ISSUE THREAD

**Issue by JoeKarow** [Virtual-Coffee/virtualcoffee.io#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

There's been chatter on Typescript Tuesdays about how there's a way to have a typesafe GraphQL client...

### Proposed solution

The current library we're using [suggests](https://github.com/prisma-labs/graphql-request#graphql-code-generators-graphql-request-typescript-plugin) a possible solution using [this GraphQL codegen](https://www.the-guild.dev/graphql/codegen/docs/getting-started) and [this plugin](https://www.the-guild.dev/graphql/codegen/plugins/typescript/typescript-graphql-request).

### Additional Resources

@tkshill @Narigo - Does this look like it could work?

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by Narigo** [comment]
There are multiple ways how to generate TypeScript types from a GraphQL introspection query. I've used a module called `graphql-codegen` in the past, which seems to be deprecated / going to be archived and they also advise you to use the proposed solution. So I guess, it's the way to go! 👍

Keep in mind that the introspection query is used by these generators usually and the introspection usually shouldn't be made available for production systems. Maybe @danieltott can advise on how this should be done then. I guess you could export introspection query results manually and then use that static version of the introspection to generate code through the codegen script.

**Comment by danieltott** [comment]
I think this is a valid idea but not really worth pursuing at this time. We've removed most of the graphql commands and manually typed the ones we use 👍
