### ISSUE TITLE
Available for work label on members page links to members page

### ISSUE THREAD

**Issue by brandonbrown4792** [Virtual-Coffee/virtualcoffee.io#63]
## Describe the bug

On the members page, the available for work labels link to the virtual coffee members page. Basically, it looks like the page is reloaded.

## To Reproduce

1. Go to the members page
2. Click on any of the Available for Work labels
3. See error

## Expected behavior

Personally, I would make it so the Available for work label did not link anywhere.

## Desktop (please complete the following information):

- OS: Mac OSX (Catalina)
 - Browser: Google Chrome
 - Version 86.0.4240.80

**Comment by brandonbrown4792** [comment]
Would you mind if I took a crack at this?

**Comment by danieltott** [comment]
Yeah I'd either do that or i think the original intention was to link to the website of the user if they had a website. Either way - go for it!

**Comment by brandonbrown4792** [comment]
Yeah. That sounds good as well. I was looking at the members page and there were already two links to the person's website (on their name and below their Github summary). So I was thinking of just making the Available for work label static text. Does that make sense? Do you agree?

**Comment by danieltott** [comment]
@brandonbrown4792 Yeah I think that's probably fine 👍

**Comment by danieltott** [comment]
Fixed via #65 
Thank you @brandonbrown4792!!

![fist bump](https://media2.giphy.com/media/RKLaxLVYKF904/giphy.gif)
