### ISSUE TITLE
Give yourself the Hacktoberfest2022 badge!

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#643]
---

### Note - only PRs from existing Virtual Coffee members participating in the Virtual Coffee Hacktoberfest Initiative will be accepted.

---

### First step - complete #13 if you haven't already!

If you haven't completed #13 already, it is perfectly fine to do that _and_ this in the same Pull Request.

### Steps:

- Find your member file (it will be `members/members/yourgithubuser.ts` where `yourgithubuser` is your user name on github.
- Near the end of the file, there is a `badges` array:
  ```js
  badges: [],
  ```
- Add `'Hacktoberfest2022'` to the array
- Save, commit, and file a Pull Request!
- Bonus: while you're in there, take a look at the `flare` section for a little bit of fun 😁

Our [original issue for adding your member profile](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13) has a lot of details about previewing locally and interacting with GitHub - definitely check that out if you'd like to preview locally!

**Comment by adiati98** [comment]
Hi @danieltott,
The link to "Our [original issue for adding your member profile](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/643#13)" is coming back to this page.
I believe it would be [this](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/13) issue?
