### ISSUE TITLE
Add Code of Conduct link to the footer

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

To make it easier to find, let's add a link to [our Code of Conduct](https://virtualcoffee.io/code-of-conduct) in the footer of the site.

### Proposed solution

In [app/components/layouts/Root.jsx](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/components/layouts/Root.jsx), add a link to `/code-of-conduct` right after the "Contact Us" link.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by adiati98** [comment]
Hi @danieltott,
Can I try and take this one? 😊

**Comment by danieltott** [comment]
@adiati98 it's all you!
