### ISSUE TITLE
Remove "Code of Conduct" section on pages where it's not relevant

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

Edit/Clarification on existing content

### Context for content change

The "Code of Conduct" block from our [Guide to VC](https://virtualcoffee.io/resources/virtual-coffee/guide-to-vc) guide accidentally got added to some other guides - they're not needed

### Proposed solution

In the [Slack Channel Guide](https://virtualcoffee.io/resources/virtual-coffee/slack-channel-guide) and the [Coding Questions Guide](https://virtualcoffee.io/resources/virtual-coffee/coding-questions-guide), remove the "Code of Conduct" section.

![image](https://user-images.githubusercontent.com/360261/193667188-ae05efcd-defb-4f22-b984-7bf9658acea1.png)

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by pedaars** [comment]
Can i pick this up?
