### ISSUE TITLE
Add lazy loading to member profile photos

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

We have [a lot of members now](https://virtualcoffee.io/members)!

In order to improve performance on that site, it would be great to lazy-load those profile images.

### Proposed solution

This is actually pretty easy these days - we can add `loading="lazy"` and `decoding="async"` to the `<img>` tag and it'll work. The problem is, as it's set now, we'll get some layout jank. The solution to this is to tell the browser what size the image is. There are a couple approaches to this - one way would be to add a `width: 100%` value to the `.membercard-img img` declaration in `styles/_members.scss` as well as an `aspect-ratio: 1` (since we know they're all square. I'm open to other solutions as well.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by Anuran12** [comment]
I would like to work on this. please assign it to me

**Comment by danieltott** [comment]
Hey @Anuran12 - we're reserving these issues for Virtual Coffee members during October. Thank you!

**Comment by YolandaHaynes** [comment]
Hi @danieltott , I would like to give this a try.

**Comment by danieltott** [comment]
@YolandaHaynes its all you!
