### ISSUE TITLE
Add Developer Health Section to Resources

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

New section on existing page

### URL of existing page

https://virtualcoffee.io/resources

### Context for content change

We need a new section of our resources that creates a new section for developer health.

Under the new section, we need a resource for "Burnout".

Based on the slack conversation, add a section for tips on burnout and give attribution to Sara and Julia: https://virtual-coffee-group.slack.com/archives/C014J8LBM5K/p1660006423888619

Add to the resources section our member Arthur Doler's talk: [The psychology of burnout](https://www.youtube.com/watch?v=-XYK8ulQId0_) 

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by AmyShackles** [comment]
Hey, what triage is still needed on this issue?  What steps need to be taken before someone can pick up this issue?  @BekahHW

**Comment by BekahHW** [comment]
@AmyShackles at the same level as the Open Source Resources on our [resource page](https://virtualcoffee.io/resources), we need the category and then underneath that Burnout, which would lead to the resources and a summary of tips, advice, support based on that slack thread.

I wonder if instead of Developer Health, it could be called Developer Life and then we could include more.

**Comment by AmyShackles** [comment]
Hey @BekahHW!  “Developer Health” _is_ more specific, but I feel like naming it “Developer Life” may be a bit too broad, considering we spend a fair bit of our lives working and it feels like this section is meant to be for things that affect developers beyond that (and might actually make it sound like a lifestyle section — Developer Liiiiife!  But maybe I’m overthinking it).  What about something like “Beyond Work”?

**Comment by BekahHW** [comment]
@AmyShackles I think beyond work is less clear. Let's go with developer health for now. As it evolves, we can rethink if we need to.

**Comment by chaos986** [comment]
Pleas assign to me
<iframe src="https://giphy.com/embed/54JLdulN5BOwM" width="480" height="284" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/54JLdulN5BOwM">via GIPHY</a></p>

**Comment by danieltott** [comment]
@AmyShackles did you want to work on this?

**Comment by AmyShackles** [comment]
@danieltott Thanks for checking!  I did not.  Was just clarifying it was ready for dev. 😉

**Comment by BekahHW** [comment]
@chaos986 it's all you! Let me know if you need any help.

**Comment by ClJarvis** [comment]
If we have just a link to add do we need to open an new issue? Or should we open a discussions so there some where to collect and sort links. That way they won't have to be added one at a time?

**Comment by BekahHW** [comment]
That's a great question, @ClJarvis! I think a discussion is a really good idea. We might find that we need to develop separate pages for topics. So collecting them will give us time to figure it out.

**Comment by ClJarvis** [comment]
@BekahHW Sounds like a good. plan.

**Comment by danieltott** [comment]
closed via #685
