### ISSUE TITLE
Convert `UndrawIllustration.jsx` to TypeScript

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#682]
## Note for Hacktoberfest:

Virtual Coffee is reserving all open issues for Virtual Coffee members for the month of October. 

[Find out more about becoming a member](https://virtualcoffee.io/join)

---

### File

[`app/components/UndrawIllustration.jsx`](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/components/UndrawIllustration.jsx)

### Issue Context

- Be sure to add some comments to the type definitions.  

  Check out this for an example of what I mean (example code compliments of @JoeKarow): https://github.com/Virtual-Coffee/virtualcoffee.io/blob/80028b4cba8b190d2931d8284f9278417e5ed82c/app/util/cmsimage.ts
  
  Those comments can include markdown and we're generally following [TSDoc](https://tsdoc.org/) - they result in nice things like this in code editors:
  
  ![image](https://user-images.githubusercontent.com/360261/195376412-53802380-3527-4d5d-bfba-2ac96aebaea6.png)

### Blockers
- _None_

**Comment by sadiejay** [comment]
I'd like to take a shot at this!
