### ISSUE TITLE
Convert `app/components/layouts/DefaultLayout.jsx` to TypeScript

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#686]
## Note for Hacktoberfest:

Virtual Coffee is reserving all open issues for Virtual Coffee members for the month of October. 

[Find out more about becoming a member](https://virtualcoffee.io/join)

---

### File

[`app/components/layouts/DefaultLayout.jsx`](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/components/layouts/DefaultLayout.jsx)

### Issue Context

- Be sure to add some comments to the type definitions.  

  Check out this for an example of what I mean (example code compliments of @JoeKarow): https://github.com/Virtual-Coffee/virtualcoffee.io/blob/80028b4cba8b190d2931d8284f9278417e5ed82c/app/util/cmsimage.ts
  
  Those comments can include markdown and we're generally following [TSDoc](https://tsdoc.org/) - they result in nice things like this in code editors:
  
  ![image](https://user-images.githubusercontent.com/360261/195376412-53802380-3527-4d5d-bfba-2ac96aebaea6.png)

### Blockers
- _none_

**Comment by danieltott** [comment]
The blockers on this are done and this one is good to go!

**Comment by aishwarya-mali** [comment]
@danieltott Can I try this one?

**Comment by danieltott** [comment]
@aishwarya-mali you got it!
