### ISSUE TITLE
Convert `cmsimage.js` to TypeScript

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#689]
## Note for Hacktoberfest:

Virtual Coffee is reserving all open issues for Virtual Coffee members for the month of October. 

[Find out more about becoming a member](https://virtualcoffee.io/join)

---

### File

[`app/util/cmsimage.js`](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/util/cmsimage.js)

### Issue Context

- Might need types for `@imgix/js-core`

### Blockers
- _None_

**Comment by JoeKarow** [comment]
I'll take this on!

**Comment by danieltott** [comment]
@JoeKarow its all you!
