### ISSUE TITLE
Convert `loadMdx.server.js` to TypeScript

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#691]
## Note for Hacktoberfest:

Virtual Coffee is reserving all open issues for Virtual Coffee members for the month of October. 

[Find out more about becoming a member](https://virtualcoffee.io/join)

---

### File

[`app/util/loadMdx.server.js`](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/util/loadMdx.server.js)

### Issue Context

- Used to load in mdx files in the remix app. 
- `loadMdxDirectory` is a recursive function - it can call itself
- Be sure to add some comments to the type definitions.  

  Check out this for an example of what I mean (example code compliments of @JoeKarow): https://github.com/Virtual-Coffee/virtualcoffee.io/blob/80028b4cba8b190d2931d8284f9278417e5ed82c/app/util/cmsimage.ts
  
  Those comments can include markdown and we're generally following [TSDoc](https://tsdoc.org/) - they result in nice things like this in code editors:
  
  ![image](https://user-images.githubusercontent.com/360261/195376412-53802380-3527-4d5d-bfba-2ac96aebaea6.png)

### Blockers
- _None_

**Comment by sadiejay** [comment]
I'd like to try this one! :)

**Comment by danieltott** [comment]
@sadiejay its all you!

**Comment by danieltott** [comment]
@sadiejay Are you still interested in this one?

**Comment by sadiejay** [comment]
Sorry I dropped this! I'd be happy to continue to tackle it with some help!
But if you don't have the bandwidth to help me like before, then you can
pass it to someone else :)

**Comment by danieltott** [comment]
@Mohsin-mw go for it!

**Comment by danieltott** [comment]
closed in https://github.com/Virtual-Coffee/virtualcoffee.io/pull/958
