### ISSUE TITLE
Create membercards macro to simplify members template

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#70]
## Issue Context

We now have three different loops where we're outputting the same markup for members. Let's abstract that out into a macro that we can call when displaying a member card.

## Suggested Solution

We'll use a [nunjucks `macro`](https://mozilla.github.io/nunjucks/templating.html#macro) for this.

Create a file called `src/_includes/macros/members.njk`, and create a macro called `membercards`. We can copy one of the `membercards` blocks from the existing `src/members.njk` template (the div `<div class="membercards">` and its contents).

`members.njk` should look something like this:

```njk
{# src/_includes/macros/members.njk #}

{% macro membercards(membersList) %}
<div class="membercards">
  {% for member in members %}
    {# template content here #}
  {% endfor %}
</div>
{% endmacro %}
```

Then in the members template, we'll need to `import` the macro at the top of the file:

```njk
{% from "macros/members.njk" import membercards %}
```

Then we can replace the existing loops with our new macro:

```njk
{# example for the Members section #}
<h2 class="mb-sm-3 mb-md-5 display-4">Our Members</h2>
{{ membercards(members) }}

```

This can be applied to all three sections where we're looping through.

**Comment by surajrpanchal** [comment]
I’ll handle this one

**Comment by danieltott** [comment]
You got it @surajrpanchal! Let me know if you have any questions along the way.

**Comment by surajrpanchal** [comment]
@danieltott I change html code as mention and observed "Founder" & "Community Engagement" sections image size is different from "our member" section. Should I make only one macro to look all of the member image same or should I make two different macro one for "Founder" & "Community Engagement" & second for "our member" section to look same as current member page

**Comment by danieltott** [comment]
@surajrpanchal the image size shouldn't be different, so there may be something else weird going on...

The markup may have gotten a little weird after the last few updates. Here's a general outline of how it should look when you're done:

```njk
<div class="bg-light py-5">
  <div class="container-xl">
    <h2 class="mb-sm-3 mb-md-4 display-4">Leadership Team</h2>
    <h3 class="mb-sm-3 mb-md-3">Our Founders</h3>
    {{ membercards(founders) }}
    <h3 class="mb-sm-3 mb-md-3">Community Engagement</h3>
    {{ membercards(founders) }}
  </div>
  <div class="container-xl">
    <h2 class="mb-sm-3 mb-md-5 display-4">Our Members</h2>
    {{ membercards(communityEngagement) }}
  </div>
</div>
```

Feel free to create a draft PR if you'd like me to review anything!

**Comment by surajrpanchal** [comment]
I have same html code but have one more div tag with Go Team!

**Comment by surajrpanchal** [comment]
@danieltott I generated PR but it has conflict can you help me to resolve it?

**Comment by danieltott** [comment]
@surajrpanchal I resolved the merge conflict - so the markup is still a bit mixed up but this isn't your fault - it had gotten mixed up a bit over the last few weeks. So - let's adjust it so it looks like this:

```njk
<div class="bg-light py-5">
  <div class="container-xl">
    <h2 class="mb-sm-3 mb-md-4 display-4">Leadership Team</h2>
    <h3 class="mb-sm-3 mb-md-3">Our Founders</h3>
    {{ membercards(founders) }}
    <h3 class="mb-sm-3 mb-md-3">Community Engagement</h3>
    {{ membercards(founders) }}

    <h2 class="mb-sm-3 mb-md-5 display-4">Our Members</h2>
    {{ membercards(communityEngagement) }}

	<div class="member-footer">...</div>
  </div>
</div>
```

So - just one `bg-light` and one `container-xl` - I think that should work out ok.

**Comment by surajrpanchal** [comment]
@danieltott  Fixed html code and committed. please have look the same PR

**Comment by danieltott** [comment]
Done in #72 
Thank you @surajrpanchal!!!

![](https://media2.giphy.com/media/Is1O1TWV0LEJi/giphy.gif)
