### ISSUE TITLE
Create macro for displaying undraw svgs

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#73]
## Issue Context

We're using really nice svgs from https://undraw.co/. Right now we're simply inserting them into templates via `include`:

```njk
{% include "svg/undraw_Add_user_re_5oib.svg" %}
```

The problem is there's no way to edit the `<title>`, and I also have been thinking it'd be nice to have the option edit the primary color. Right now they all have the same primary color (`#d9376e`). There may be some other attributes it'd be nice to have dynamic as well (maybe `id` and `class`?).

## Suggested Solution

Create a [nunjucks macro](https://mozilla.github.io/nunjucks/templating.html#macro) for displaying undraw svgs. I'd think the usage could look something like this:

```njk
{{ undrawSvg('undraw_Add_user_re_5oib.svg', {
  title: 'This is our title!'
}) }}

{# optionally change the primary color: #}
{{ undrawSvg('undraw_Add_user_re_5oib.svg', {
  title: 'This is our title!',
  color: '#dd7123' {# or currentColor even! #}
}) }}
```

## Alternatives Considered

We probably could achieve the color thing via css and create some classes - then instead of passing a color we could just pass a class or some value from an enum (`primary,secondary,etc`). I'm open to anything here. 

Can't really think of a better solution for the `<title>` situation though.

Just as a note, when I download svgs from undraw, they have a nice feature to set the primary color, but I have had to make sure to delete the `height` and `width` attributes. It might be nice to be able to just download them straight in and have the macro take care of them, but I can't think of a reasonable solution to this so I'm fine punting on it for now.

**Comment by sethburtonhall** [comment]
🖐🏻 I'll take this one

**Comment by manthony9** [comment]
@danieltott  Got it! I was trying to edit the svg's without having to change the file manually 😂...Working on it now..

**Comment by manthony9** [comment]
Hi @danieltott I've solved for the title problem using your approach. Do you think we could use the same approach for the fill ? Each Undraw svg has multiple fills with and without #d9376e as their fill color.  I could add a variable for each instance where we have #d9376e or maybe add an ID to the paths with #d9376e ?
