### ISSUE TITLE
Set up a better build system

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#74]
## Issue Context

In the interest of getting this out the door as quick as possible, I wired this up using an existing [`GruntJS`](https://gruntjs.com/) setup I had and then bolted 11ty on top of it. Grunt is super out of date and we're not using some of the nicer features that come along with 11ty, but it does work. 

I'd like to see a more modern build system going here. Unfortunately 11ty doesn't have anything for assets, which is what I'd really like.

Here's what the current system has that I don't want to lose:

- `npm start` creates a local server and automatically rebuilds for local development
- `npm build` creates a production-ready build
- `sass` support
- JS concat/minification/etc/maybe? There's literally no javascript on the site right now, but grunt is set up to do simple concat/uglify. One of the reasons I didn't just jump in with Parcel et al is that to get styles you have to create a javascript file and import the css file. It's _possible_ I'm overthinking this.
- postCSS support so we can run things like autoprefixer, purge, and nano
- cache-busting via filename hashes
- hooked in to 11ty somehow

There's a lot of funky variables in play here. 

The things I am optimizing for:

- **Very very easy to use as a contributor**
  This is the biggest one. Should be able to `npm install` and then `npm start` and get to work without having to think about or understand what the build system is doing.
- Highly optimized output
  The main reason to use 11ty is to have a small and fast site. We're very close to a perfect lighthouse score, and I don't want the build system to affect that negatively.
- Can adjust down the line
  This is the biggest issue with the current setup - it's a house of cards ready to fall down. Grunt (and plugins) are very outdated, and if we add new features here it'll end up being really difficult to get grunt to work with them.

If you'd like to contribute to this issue, let's start a discussion here before getting to work so we can discuss approaches etc.

**Comment by meg-gutshall** [comment]
I'm going to hit you up in Slack re: this issue.

**Comment by danieltott** [comment]
Here's another path that is looking more and more attractive to me:

Use a combination of node scripts and [11ty Events](https://www.11ty.dev/docs/events/) to build assets within the existing 11ty setup.

I think this could work pretty well. All of the asset stuff we're doing in grunt currently is pretty simple and can be extracted out. Use the 11ty events to run things pre-build/post-build/or during a watch event. The watch hook even will provide a list of changed files, so we could selectively run parts of the build instead of just re-running the entire thing. Food for thought.

**Comment by shiftyp** [comment]
☝🏻 Bringing the above PR's to your attention as well @meg-gutshall. Would love your feedback!

**Comment by danieltott** [comment]
No longer needed - moving to Remix #545
