### ISSUE TITLE
Add section to events page about our youtube page

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

There's not a ton of visibility to our [YouTube channel](https://youtube.com/@VirtualCoffeeIO) on the site - I think a good spot for this would be the top of the [events page](https://virtualcoffee.io/events).

### Proposed solution

The simplest solution would be an additional paragraph in the intro section saying something like "many of our events are recorded, you can find them here". Or maybe a little bit more calling out some of our playlists/series...

Bonus points:

~Not sure if this is a good idea or not, but we could pull in the latest x videos and display bigger thumbnails links to them? I don't think I'd want to embed videos but certainly grabbing some data in the loader and displaying them here could be cool. This would take some more design thought obviously, and it might not even work visually, so if someone took this part on, you'd have to be ok with possibly trashing the work at the end if that's what happens.~

~This would need to be a server-side thing (done in the loader), not a client-side thing. IE I won't want to be loading any client-side js from youtube.~

Edit: Doing this later

### Additional Resources

- [YouTube Data API Node.js Quickstart](https://developers.google.com/youtube/v3/quickstart/nodejs)
- [remix loaders](https://remix.run/docs/en/v1/api/conventions#loader)

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by adiati98** [comment]
@danieltott can I take this issue?

Just a thought, I'm thinking for now maybe just give link to our YouTube channel without giving thumbnails.
I think we were talking about redesigning our website? (or not?)
Maybe at that time then we can think if we want to add thumbnails or something like that.

**Comment by danieltott** [comment]
@adiati98 it's all you! 

I think that's fine - let's just make sure the callout is nice and visible 😁

**Comment by adiati98** [comment]
Thanks, @danieltott !
I'll do this by next week 😊
