### ISSUE TITLE
Add link to `/register` on `/login` page

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

If a user lands on https://virtualcoffee.io/login but doesn't have an account already, we should provide a link to https://virtualcoffee.io/register

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by creaturenex** [comment]
I would like to take this on.

**Comment by danieltott** [comment]
@creaturenex it's all you!

**Comment by danieltott** [comment]
@creaturenex how's this going? Need some help?

**Comment by creaturenex** [comment]
Dan sorry about this, just got accepted into a code school and had no time to allocate to this problem
