### ISSUE TITLE
Add Code of Conduct Violation Report link to Code of Conduct page

### ISSUE THREAD

**Issue by meg-gutshall** [Virtual-Coffee/virtualcoffee.io#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

New section on existing page

### URL of existing page

https://virtualcoffee.io/code-of-conduct

### Context for content change

It's difficult to find the violation form. Adding this will make it easier.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment]
@meg-gutshall - this looks like a duplicate of #703 (which was closed via #719). Can you be more specific about changes you'd like to see? Or can we close this one?

**Comment by meg-gutshall** [comment]
Ahh... you are correct! My bad!
