### ISSUE TITLE
Separate Burnout from Developer Health

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#813]
Currently, our Developer Health page is home to burnout resources. As we develop this section, let's reorganize to make it easier to find resources.

Similar to the [Open Source Resources](https://virtualcoffee.io/resources/virtual-coffee/get-involved) page, let's make Developer Health the main page. You can use [this](https://github.com/Virtual-Coffee/virtualcoffee.io/tree/main/app/routes/__frontend/resources/open-source) as a guide to separate the Burnout Section. 

Within the [Developer Health](https://github.com/Virtual-Coffee/virtualcoffee.io/tree/main/app/routes/__frontend/resources/developer-health) folder, you'll now have an `index.mdx` file and a `burnout.mdx` file that has the information currently in the `index` file.

**Comment by aishwarya-mali** [comment]
@BekahHW Please assign this issue to me.
