### ISSUE TITLE
Add Resources to How to Ask questions About Your Code

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#815]
We have some VC-member-created resources that can help people learn.

In the [before asking question section](https://virtualcoffee.io/resources/virtual-coffee/coding-questions-guide#before-asking-question), add links to @nickytonline's Lunch & Learns 

- Debugging with  JavaScript: https://youtu.be/I9A0Pifn0Uw
- Web Dev Debugging Hour - coming to YT soon.

**Comment by adiati98** [comment]
Hey @BekahHW 
Can I work on this one? 😊

**Comment by danieltott** [comment]
@adiati98 it's all you!
