### ISSUE TITLE
Add /uses page

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#84]
## Issue Context

https://uses.tech/

It'd be cool to add a `/uses` page to display the tech we use to create the site.

## Suggested Solution

Create a page with the url `/uses`!

I'd be happy to help review/collect/suggest things to add if needed.

## Additional Resources

Some great examples in the wild:

- https://www.iamdeveloper.com/uses/ (@nickytonline ❤️ )
- https://vicvijayakumar.com/uses (@needcaffeine ❤️ )

**Comment by danieltott** [comment]
Once it's live, we could submit it to https://github.com/wesbos/awesome-uses

**Comment by Cerchie** [comment]
Would love to work on this!

**Comment by danieltott** [comment]
@Cerchie It's all you! Let me know how I can help!
