### ISSUE TITLE
Add All Contributors to Repo

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#878]
We can add more recognition for our contributors by using [All Contributors](https://allcontributors.org/docs/en/bot/installation).

We can add more specific details by using [emojis](https://allcontributors.org/docs/en/emoji-key) to showcase what types of contributions as well.

This [maintainers info](https://allcontributors.org/docs/en/repository-maintainers) is a good read.

**Comment by danieltott** [comment]
@BekahHW go for it!

**Comment by BekahHW** [comment]
Can I be assigned this issue? @danieltott

**Comment by danieltott** [comment]
You again??

**Comment by CBID2** [comment]
If this issue is still available, can I create a pull request for this and count it towards Hacktoberfest?
