### ISSUE TITLE
Reorganize VC resources

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

Edit/Clarification on existing content

### URL of existing page

https://virtualcoffee.io/resources/virtual-coffee

### Context for content change

We have a lot going on at VC --which is great-- and it’s kind of hard to discover what’s going on, especially for new members.

### Proposed solution

- Guide To Virtual Coffee should be top-level with children
- Many sections in that can be pulled out into their own pages that would live under “Guide to VC”
- Move Channel guide under “guide to VC”
  Order should be:
  - Join VC
  - Guide to VC
  - Get Involved
- Move how to ask questions to dev resources

On that last point, there’s a section that is specific to VC that I think we can pull out and maybe add to the channel guide or something like that, the rest of the content is great for general resources

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by adiati98** [comment]
@danieltott I have a couple questions (for now 😝) to clarify things:

1. Bullet point 1: 
    > Guide To Virtual Coffee should be top-level with children

    Which children are we talking about?

2. When I already understand the point above:
    > Many sections in that can be pulled out into their own pages that would live under “Guide to VC”
    
    Do you mean that we should make new independent pages for the sections and put them under "Guide to VC"? 

Thanks in advance! 😀

**Comment by danieltott** [comment]
The children will be the new pages that you create from content inside the guide, as well as the Channel Guide

Hopefully that makes sense!

**Comment by adiati98** [comment]
> The children will be the new pages that you create from content inside the guide, as well as the Channel Guide
> 
> Hopefully that makes sense!

Ummmm... I still don't get it 🙈
Sorry 😅

**Comment by danieltott** [comment]
So the new structure could be something like this:

- Join Virtual Coffee
- Guide To Virtual Coffee
  - Virtual Coffee Slack Channel Guide
  - What To Expect In Virtual Coffee
  - Coffee Table Groups
  - Monthly Challenges
  - Lunch & Learns
  - Lightning Talks
  - HacktoberFest
  - Giving Back To The Community
  - Keeping Up With Virtual Coffee
- Get Involved
  - Paths to Leadership & Roles
  - Leading a Coffee Table Group
  - Lunch and Learns


Most of the new pages under "Guide to Virtual Coffee" can be created by removing content from the original guide and adding it as a new page. For instance - a new page called "Coffee Table Groups" that would be created from the content [here](https://virtualcoffee.io/resources/virtual-coffee/guide-to-vc#coffee-table-groups).

If I'm still not explaining this well we can meet up if you want!
