### ISSUE TITLE
Add Discussion Category Form for CSS Battles discussions

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#900]
Github now has Discussion Category Forms (similar to issue forms) for discussion categories!

Let's add a discussion form for CSS Battles to make it easier to post our css battles.

- [GitHub Discussion Category Forms blog post](https://github.blog/2023-01-09-github-discussions-just-got-better-with-category-forms/)
- [GitHub Discussion Category Forms docs](https://docs.github.com/en/discussions/managing-discussions-for-your-community/creating-discussion-category-forms)
- [VC CSS Battles discussion category](https://github.com/orgs/Virtual-Coffee/discussions/categories/css-battles)

What I would love to see (and I'm not sure if this is possible) is a way to easily paste in our code and then have the discussion form template add formatting similar to [our guidelines for css battles discussions](https://github.com/orgs/Virtual-Coffee/discussions/833).

I haven't tried out discussion category forms yet - so there may be some bits I'm not following or they may not ultimately add value for us, but I think it's worth a shot!

**Note:** Virtual Coffee's [main discussion board](https://github.com/orgs/Virtual-Coffee/discussions) is an org-level discussion board, so the file will go directly in this repository, as opposed to `/.github/...` in another repo. For more information, see "[Creating a default community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)."

## Acceptance criteria:
- Add a `DISCUSSION_TEMPLATE/css-battles.yml` file that makes it easier to share our results!

**Comment by meg-gutshall** [comment]
@piotrszymaniec

**Comment by piotrszymaniec** [comment]
:)

**Comment by meg-gutshall** [comment]
@danieltott We merged this into the Testing-Thing repo. Can you add @piotrszymaniec as an Assignee as well so he can open a PR against this Issue?

**Comment by danieltott** [comment]
@meg-gutshall @piotrszymaniec done!
