### ISSUE TITLE
Add new monthly challenge

### ISSUE THREAD

**Issue by BekahHW** [Virtual-Coffee/virtualcoffee.io#906]
We're running a brand new challenge for June and we need to get it live on the monthly challenge page of the site.

Here's the copy:

> The Mid-Year Check-In challenge is designed to provide an opportunity for Virtual Coffee members to reflect on their progress, reevaluate goals, and gain clarity on their journey. Let’s pause, assess, and adjust as we reach the halfway point of the year. This challenge aims to encourage personal growth, foster connection within the community, and provide a supportive space for members to share their insights, challenges, and successes.

To make the updates, go to `app/routes/__frontend/monthlychallenges/index.tsx`

Set `current: true,` and remove that from the Pairing challenge.

**Comment by aishwarya-mali** [comment]
@BekahHW I can work on this issue.
