### ISSUE TITLE
Font Responsiveness in Smaller Screen

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/virtualcoffee.io#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

- Some pages have horizontal scroll in mobile phone (smaller screen). It happens because of the `<h2>` font size. Please screen record attached.

https://github.com/Virtual-Coffee/virtualcoffee.io/assets/45172775/eb3589b4-bdb0-4754-b8e1-8f187f2421f2

- The font size of `<h1>` looks much smaller than `<h2>`.
- **This one is a friendly suggestion**: It would be nice to have top margin/padding for `<h1>`  to seperate it from the hero image.

  Please see screenshots attached for two points above:

`<h1>` 

  ![h1](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/45172775/95af43b1-6a56-4002-99ff-868fdb0248c1)

 `<h2>`

  ![h2](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/45172775/6f7bd891-bdba-4674-9889-589420f40380)

### Steps To Reproduce

1. Open [Burnout page on VC website](https://virtualcoffee.io/resources/developer-health/burnout) on mobile phone.
2. Now you can see that there's a horizontal scroll on the page, and the `<h2>` font looks bigger than the `<h1>`.

### What browsers are you seeing the problem on?

Chrome

### Environment

```markdown
- OS: Android 13
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by adiati98** [comment]
@danieltott if we want to fix this, can I have thiss issue? I want to learn and play around with Bootsrap/Tailwind 🙂

**Comment by danieltott** [comment]
@adiati98 I'm sorry, I totally missed your comment here. Do you still want this one?

**Comment by adiati98** [comment]
Yes, please @danieltott 😃
