### ISSUE TITLE
Add 301 redirects for content that has been relocated

### ISSUE THREAD

**Issue by dominicduffin1** [Virtual-Coffee/virtualcoffee.io#945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

I noticed the other day that the old link to the Open Source resources [https://virtualcoffee.io/resources/open-source](https://virtualcoffee.io/resources/open-source) leads to a 404 page. It would be great if when someone clicks on an out of date link they get redirected to the up to date page.

### Proposed solution

Add 301 redirects for pages that have moved after a site reorganization.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by adiati98** [comment]
@dominicduffin1, remembering that we and other folks still use old links out there (blog posts, older newsletters, etc.), I like this idea 💡!
It would also be good for our SEO.

@danieltott, any thoughts?

**Comment by dominicduffin1** [comment]
I can work on this later in the month if you want to assign me @danieltott

**Comment by danieltott** [comment]
@dominicduffin1 thank you! It's all you 👍🏼
