### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by bL34cHig0** [Virtual-Coffee/virtualcoffee.io#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Context for documentation change

I noticed a grammatical error on the first line of the Resources section in the README file.

![image](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/133022207/18cd3dd1-6cbf-4117-b80f-2d8aedb2c466)

### Proposed solution

"are creating" should be changed to "are created" in the first line.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community
```[tasklist]
### Tasks
```

**Comment by bL34cHig0** [comment]
I'd like to be assigned to this task if permitted. Thank you

**Comment by danieltott** [comment]
@bL34cHig0 go for it 👍

**Comment by bL34cHig0** [comment]
Thank you @danieltott, working on it
